"""
Cybersecurity - The Watchtower. Ten levels, data only.
"""

from courses.common import level


CYBER_LEVELS = [

    level(
        1, "What Is Cybersecurity?",
        objective="Explain what cybersecurity protects and why.",
        concepts=["assets", "confidentiality", "integrity", "availability"],
        story="You are loaded onto the Watchtower wall. BYTE: 'Everything worth protecting is an asset. Our job is to keep assets safe.'",
        goal="Identify which item is an asset the Academy must protect.",
        learn=[
            "Cybersecurity protects assets: data, accounts, devices, services.",
            "Three goals: keep secrets secret (confidentiality), keep data correct (integrity), keep systems working (availability).",
        ],
        example="Asset: student accounts\nThreat: password guessing\nDefence: strong passwords + lockout",
        dialogue=[
            "Welcome to the Watchtower. We guard the Academy's assets.",
            "An asset is anything valuable: data, accounts, the servers themselves.",
            "Tell the gate terminal which of its options is an asset.",
        ],
        challenge={
            "type": "mcq",
            "prompt": "Which of these is an ASSET the Academy must protect?",
            "options": ["The weather outside", "The database of student accounts", "A rumour about NULL", "The colour of the wall"],
            "answer": 1,
            "wrong": "An asset is something valuable to the organisation that could be stolen, changed or taken offline.",
        },
        reasoning="Separating what matters (assets) from noise is the first security skill.",
        success="The gate recognises you as a defender.",
        failure="Feedback restates what an asset is.",
        explanation="Student accounts hold private data and grant access - losing them breaks confidentiality and integrity.",
        reward="Watch Badge I",
        mentor="Explain assets and the three goals with everyday examples.",
        hints=["Which option would hurt the Academy if it were stolen?"],
        intro=True,
    ),

    level(
        2, "Threats Online",
        objective="Recognise common ways people get compromised online.",
        prerequisites=["assets"],
        concepts=["threats", "attack surface", "risk"],
        story="Scouts report strange messages hitting the Academy's inboxes. BYTE lists the usual suspects.",
        goal="Pick the situation that is most likely an attack.",
        learn=[
            "A threat is anything that could harm an asset.",
            "The attack surface is every way in: email, links, downloads, weak passwords, public Wi-Fi.",
            "Risk = how likely x how bad.",
        ],
        example="Unexpected link + urgency + asks for login  ->  high risk",
        dialogue=["Threats come through every door: links, attachments, passwords, open networks.", "Spot the one that smells like an attack."],
        challenge={
            "type": "mcq",
            "prompt": "Which situation is MOST likely an attack?",
            "options": [
                "A friend messages to ask about homework",
                "An unknown sender says your account will close in 1 hour unless you log in via their link",
                "Your OS asks to install a security update",
                "A website loads slowly",
            ],
            "answer": 1,
            "wrong": "Look for urgency, an unknown sender, and a request to log in somewhere.",
        },
        reasoning="Urgency + unknown sender + credentials request is the signature of most attacks.",
        success="The scout report is filed correctly.",
        failure="Feedback lists the three warning signs.",
        explanation="Attackers rush you so you skip thinking. Legit services rarely demand logins through unexpected links.",
        reward="Watch Badge II",
        mentor="Discuss warning signs of risky messages.",
        hints=["Which option pushes you to act fast?"],
    ),

    level(
        3, "Authentication vs Authorization",
        objective="Distinguish proving who you are from what you are allowed to do.",
        concepts=["authentication", "authorization"],
        story="The inner keep has two checkpoints: one checks your badge, the other checks your rank.",
        goal="Name the process that proves WHO you are.",
        learn=[
            "Authentication = proving identity (password, badge, fingerprint).",
            "Authorization = what that identity is allowed to do.",
            "You always authenticate first, then get authorized.",
        ],
        example="Login with password  -> authentication\nOnly admins delete users -> authorization",
        dialogue=["Checkpoint one asks WHO you are. Checkpoint two asks WHAT you may do.", "Two different words. Tell the terminal the first one."],
        challenge={
            "type": "text_answer",
            "prompt": "Showing your badge to prove who you are is called...",
            "placeholder": "one word",
            "accepted": ["authentication", "authenticate", "authenticating"],
            "wrong": "Authorization is about permissions. Proving identity is the other one.",
        },
        reasoning="Keeping the two ideas separate prevents classic access-control mistakes later.",
        success="Both checkpoints open.",
        failure="Feedback contrasts identity vs permission.",
        explanation="Authentication answers 'who are you?'; authorization answers 'what may you do?'. This app's login is authentication; login_required is authorization.",
        reward="Watch Badge III",
        mentor="Give examples from the Cyber Academy app itself (login vs login_required).",
        hints=["It starts with authentic-."],
    ),

    level(
        4, "Password Security",
        objective="Judge password strength and understand entropy.",
        prerequisites=["authentication"],
        concepts=["length", "variety", "entropy", "password managers"],
        story="The armoury lock accepts a new passphrase. Your signup screen already measured entropy - now apply it.",
        goal="Choose the strongest password.",
        learn=[
            "Length beats cleverness: every extra character multiplies the guesses needed.",
            "Variety (upper, lower, digits, symbols) raises entropy - the unpredictability per character.",
            "Never reuse passwords; let a password manager remember them.",
        ],
        example="password123      -> weak, common\nTr3e-Lantern!Grove9 -> long + varied = strong",
        dialogue=["Remember the entropy meter when you signed up? Same idea.", "Long and varied wins. Pick the strongest."],
        challenge={
            "type": "mcq",
            "prompt": "Which password is the strongest?",
            "options": ["password123", "Grove2024", "Tr3e-Lantern!Grove9", "qwerty!"],
            "answer": 2,
            "wrong": "Think length first, then variety. Common words and patterns are guessed instantly.",
        },
        reasoning="Applying length and variety, not just 'has a symbol'.",
        success="The armoury locks with the new passphrase.",
        failure="Feedback explains why the chosen one is guessable.",
        explanation="Tr3e-Lantern!Grove9 is long and mixes cases, digits and symbols - far more possible combinations than the others.",
        reward="Watch Badge IV",
        mentor="Relate to Shannon entropy shown at signup; avoid asking the player for their real passwords.",
        hints=["Which one is the longest?"],
    ),

    level(
        5, "Social Engineering",
        objective="Recognise manipulation that targets people, not machines.",
        prerequisites=["threats"],
        concepts=["pretexting", "urgency", "authority", "verification"],
        story="A stranger at the gate claims to be the Headmaster's assistant and needs the tower key 'right now'.",
        goal="Choose the safe response.",
        learn=[
            "Social engineering tricks people into giving access.",
            "Tools: fake authority, urgency, friendliness, fear.",
            "Defence: slow down and verify through a channel you trust.",
        ],
        example="'I'm from IT, give me your password' -> IT never needs your password.",
        dialogue=["Not every attack is code. Some are conversations.", "Someone is asking for the key. What do you do?"],
        challenge={
            "type": "mcq",
            "prompt": "The 'assistant' insists you hand over the key immediately. Safest action?",
            "options": [
                "Hand it over - they sound important",
                "Verify with the Headmaster through the official channel before doing anything",
                "Give a copy but keep the original",
                "Ask them to promise they are honest",
            ],
            "answer": 1,
            "wrong": "Authority and urgency are the trick. Verification through a trusted channel breaks it.",
        },
        reasoning="Recognising the pressure tactics and choosing verification.",
        success="The impostor leaves. The key stays safe.",
        failure="Feedback names the pressure tactic used.",
        explanation="Attackers borrow authority and urgency. Verifying independently costs a minute and defeats the attack.",
        reward="Watch Badge V",
        mentor="Discuss pressure tactics and how to verify safely.",
        hints=["What would you do if you could not be fooled by a job title?"],
    ),

    level(
        6, "Phishing",
        objective="Spot the tell-tale sign in a phishing email.",
        prerequisites=["social engineering"],
        concepts=["phishing", "spoofed links", "sender checks"],
        story="An email arrives 'from' the Academy. BYTE freezes it on the tower screen so you can inspect it line by line.",
        goal="Click the line that gives the phish away, then say why.",
        learn=[
            "Phishing = fake messages that steal logins or install malware.",
            "Check: the real sender address, where links actually go, spelling, urgency.",
            "Never log in from a link in an unexpected email - go to the site yourself.",
        ],
        example="Displayed: academy-login.com   Actual: academy-login.evil-site.ru",
        dialogue=["Frozen email on screen. One line gives it away.", "Look at where the link REALLY goes."],
        challenge={
            "type": "code_review",
            "label": "EMAIL",
            "prompt": "Click the suspicious line, then choose why.",
            "code": [
                "From: Cyber Academy <security@cyber-acadmey-alerts.ru>",
                "Subject: Your account will be deleted TONIGHT",
                "Dear student, we detected a problem.",
                "Click here to keep your account: http://acad-login.evil-site.ru/login",
                "Thank you, Academy Security",
            ],
            "target_line": 4,
            "why_options": [
                "The link points to a domain that is not the Academy's",
                "Emails should never have a subject",
                "'Dear student' is too polite",
                "Security teams never sign emails",
            ],
            "why_answer": 0,
            "fixed": [
                "Safe habit: do not click. Open the Academy site yourself",
                "and log in there. Report the email to security.",
            ],
        },
        reasoning="Checking the real destination of a link instead of trusting the text.",
        success="The email is quarantined.",
        failure="Feedback: check sender address and link destination, not the wording.",
        explanation="The link goes to evil-site.ru. The misspelled sender domain is a second clue. Urgency is the pressure.",
        reward="Watch Badge VI",
        mentor="Coach on inspecting links and sender addresses.",
        hints=["Where does the link actually go?", "Read the sender address letter by letter."],
    ),

    level(
        7, "Firewalls",
        objective="Understand that a firewall applies allow/deny rules to traffic.",
        concepts=["firewall", "rules", "allow", "deny", "default deny"],
        story="The outer wall gate has a rulebook. Traffic that matches no rule must be denied.",
        goal="Decide the gate's verdict for unknown traffic.",
        learn=[
            "A firewall checks each connection against rules: source, destination, port.",
            "Good practice: default deny - block everything not explicitly allowed.",
        ],
        example="ALLOW  anyone -> web server : 443\nDENY   everything else",
        dialogue=["The gate checks every packet against its rules.", "A packet from an unknown source wants the admin port. No rule allows it. Verdict?"],
        challenge={
            "type": "text_answer",
            "prompt": "Unknown source -> admin port. No rule allows it. Verdict: allow or deny?",
            "placeholder": "allow / deny",
            "accepted": ["deny", "denied", "block", "blocked", "drop"],
            "wrong": "Default deny: if nothing explicitly allows it, it does not pass.",
        },
        reasoning="Applying default-deny thinking.",
        success="The gate drops the packet.",
        failure="Feedback restates default deny.",
        explanation="Firewalls should allow only what is needed. Everything else - including unknown traffic to sensitive ports - is denied.",
        reward="Watch Badge VII",
        mentor="Explain allow-lists vs deny-lists.",
        hints=["What is the safe default when no rule matches?"],
    ),

    level(
        8, "Malware",
        objective="Identify malware types by behaviour.",
        prerequisites=["threats"],
        concepts=["virus", "ransomware", "spyware", "trojan"],
        story="A courier's laptop is encrypting its own files and demanding coins.",
        goal="Name the type of malware.",
        learn=[
            "Malware = malicious software.",
            "Ransomware encrypts files and demands payment. Spyware watches you. Trojans hide inside useful-looking programs. Viruses spread by attaching to files.",
        ],
        example="Files renamed .locked + payment note -> ransomware",
        dialogue=["The laptop is locking its own files and asking for coins.", "Which malware behaves like that?"],
        challenge={
            "type": "mcq",
            "prompt": "Files are being encrypted and a payment note appears. This is:",
            "options": ["Spyware", "Ransomware", "A firewall", "A password manager"],
            "answer": 1,
            "wrong": "Encrypt + demand payment is the signature of one specific type.",
        },
        reasoning="Matching behaviour to category.",
        success="The laptop is isolated before it spreads.",
        failure="Feedback lists each type's behaviour.",
        explanation="Ransomware encrypts data and extorts payment. Defence: backups, updates, no unknown attachments.",
        reward="Watch Badge VIII",
        mentor="Explain malware types with defensive advice only.",
        hints=["Ransom means demanding payment."],
    ),

    level(
        9, "Incident Response",
        objective="Know the first step when an attack is discovered.",
        prerequisites=["malware"],
        concepts=["identify", "contain", "eradicate", "recover", "learn"],
        story="Alarm! A tower node is compromised. Everyone looks at you.",
        goal="Choose the correct first action.",
        learn=[
            "Incident response steps: Identify -> Contain -> Eradicate -> Recover -> Learn.",
            "Contain first (disconnect it) so the damage stops spreading.",
        ],
        example="1 Identify  2 Contain  3 Eradicate  4 Recover  5 Lessons learned",
        dialogue=["A node is compromised. Panic helps nobody.", "After confirming it's real, what comes first?"],
        challenge={
            "type": "mcq",
            "prompt": "You confirm a node is infected. Best FIRST action?",
            "options": ["Delete all logs so nobody sees", "Disconnect the node from the network to contain it", "Restore from backup immediately", "Post about it online"],
            "answer": 1,
            "wrong": "Stop the spread before you clean or restore. Never destroy evidence.",
        },
        reasoning="Ordering response steps and preserving evidence.",
        success="The infection is contained.",
        failure="Feedback explains why containment precedes recovery.",
        explanation="Containment limits damage; eradication and recovery come after; logs are evidence and must be kept.",
        reward="Watch Badge IX",
        mentor="Walk through the response phases.",
        hints=["Which action stops the problem from spreading?"],
    ),

    level(
        10, "Final Defense: NULL",
        objective="Apply everything: read a log and find the intrusion.",
        prerequisites=["all Watchtower levels"],
        concepts=["log review", "pattern recognition"],
        story="NULL itself hammers the gate. The only clue is the tower's access log.",
        goal="Find the log line that reveals the attack and explain it.",
        learn=["Logs record who did what and when.", "Look for repeated failures, odd times, unknown accounts."],
        example="03:12 login FAILED admin\n03:12 login FAILED admin\n03:13 login OK admin  <- suspicious after many failures",
        dialogue=["NULL is here. Read the log. Find the break-in.", "Many failures followed by success is a classic sign."],
        challenge={
            "type": "code_review",
            "label": "ACCESS LOG",
            "prompt": "Click the line that reveals the intrusion, then choose why.",
            "code": [
                "09:02 login OK      student_ada",
                "09:15 login OK      student_ben",
                "03:11 login FAILED  admin (x48 attempts)",
                "03:12 login OK      admin from 185.203.x.x",
                "08:00 backup completed",
            ],
            "target_line": 4,
            "why_options": [
                "A successful admin login right after 48 failures from an unknown address = password guessing that worked",
                "Backups should never run",
                "Students must not log in before 10:00",
                "Login OK lines are always attacks",
            ],
            "why_answer": 0,
            "fixed": ["Response: contain (disable admin, block the IP),", "reset credentials, enable lockout + 2FA, review logs."],
        },
        reasoning="Combining authentication, password and incident-response knowledge.",
        success="NULL is repelled. The Watchtower stands.",
        failure="Feedback: look at what happens right after the failures.",
        explanation="48 failed attempts then success from a foreign IP is brute-force that succeeded. Lockout and 2FA would have stopped it.",
        reward="Watchtower Master Badge",
        mentor="Help the player connect brute force, lockout, and containment.",
        hints=["Which line follows a burst of failures?"],
        boss=True,
    ),
]
