"""
Internet Fundamentals - The Relay. Ten levels, data only.
"""

from courses.common import level


INTERNET_LEVELS = [

    level(
        1, "What Is the Internet?",
        objective="Describe the internet as a network of networks.",
        concepts=["network", "connections", "protocols"],
        story="You materialise at the Relay - a field of signal towers. BYTE: 'Every tower talks to others. That is all the internet is: connected networks agreeing on rules.'",
        goal="Pick the best description of the internet.",
        learn=["The internet is many networks connected together.", "Devices agree on shared rules (protocols) so they understand each other."],
        example="Your laptop -> home router -> ISP -> ... -> a server far away",
        dialogue=["Welcome to the Relay.", "Towers talk to towers. Networks join networks. Tell the console what that is."],
        challenge={
            "type": "mcq",
            "prompt": "The internet is best described as:",
            "options": ["One giant computer", "A network of networks that share rules", "A website", "A cable under the sea"],
            "answer": 1,
            "wrong": "No single machine owns it - it is many networks agreeing on protocols.",
        },
        reasoning="Replacing the 'one big thing' mental model.",
        success="The first tower lights up.",
        failure="Feedback corrects the model.",
        explanation="The internet links independent networks using shared protocols; no single computer or company is 'the internet'.",
        reward="Relay Badge I",
        mentor="Use analogies (postal system, roads).",
        hints=["Think plural."],
        intro=True,
    ),

    level(
        2, "Clients and Servers",
        objective="Identify who requests and who responds.",
        concepts=["client", "server", "request", "response"],
        story="A courier drone asks the tower for a map; the tower hands it over.",
        goal="Name the role that ASKS for data.",
        learn=["Client: asks (your browser).", "Server: answers (the website's computer).", "Request goes out, response comes back."],
        example="Browser (client) --request--> Server --response--> Browser",
        dialogue=["The drone asked. The tower answered.", "The one who asks is the..."],
        challenge={
            "type": "text_answer",
            "prompt": "The device that sends a request for a web page is the:",
            "placeholder": "client / server",
            "accepted": ["client", "the client"],
            "wrong": "The server answers. The one asking is the other role.",
        },
        reasoning="Roles are about behaviour, not machine size.",
        success="The courier gets its map.",
        failure="Feedback restates ask vs answer.",
        explanation="Your browser is the client; it requests. The server responds. Even a phone can be a server if it answers requests.",
        reward="Relay Badge II",
        mentor="Explain request/response with the Cyber Academy app as the example.",
        hints=["When you open a site, are you asking or answering?"],
    ),

    level(
        3, "IP Addresses",
        objective="Recognise a valid IPv4 address.",
        concepts=["IP address", "IPv4 format"],
        story="Every tower has a numeric address. A courier holds four labels - only one is a real address.",
        goal="Choose the valid IPv4 address.",
        learn=["An IPv4 address is four numbers 0-255 separated by dots.", "It identifies a device on a network, like a street address."],
        example="192.168.1.10  -> valid\n192.168.300.1 -> not valid (300 > 255)",
        dialogue=["Four numbers, each 0 to 255, dots between.", "Pick the one that follows the rule."],
        challenge={
            "type": "mcq",
            "prompt": "Which is a valid IPv4 address?",
            "options": ["192.168.1.10", "192.168.300.1", "192.168.1", "relay.tower"],
            "answer": 0,
            "wrong": "Four parts, each between 0 and 255.",
        },
        reasoning="Applying the format rule.",
        success="The courier finds the tower.",
        failure="Feedback explains the 0-255 rule.",
        explanation="192.168.1.10 has four numbers in range. 300 is too big; three parts is too few; names are not IPs (that is DNS's job).",
        reward="Relay Badge III",
        mentor="Explain IPv4 format; mention IPv6 exists but keep it simple.",
        hints=["Count the parts and check each is 255 or less."],
    ),

    level(
        4, "DNS",
        objective="Explain what DNS does.",
        prerequisites=["IP addresses"],
        concepts=["DNS", "domain names", "lookup"],
        story="Nobody remembers numbers. The Relay keeps a directory tower that turns names into addresses.",
        goal="Say what DNS turns a domain name into.",
        learn=["DNS = the internet's phone book.", "You type a name (academy.example); DNS finds the IP address."],
        example="academy.example  --DNS-->  203.0.113.7",
        dialogue=["Names for humans, numbers for machines.", "DNS translates the name into a..."],
        challenge={
            "type": "text_answer",
            "prompt": "DNS translates a domain name into an ...",
            "placeholder": "two words",
            "accepted": ["ip address", "ip", "an ip address", "ip addresses", "ipaddress"],
            "wrong": "Think of the numeric label from the previous level.",
        },
        reasoning="Linking names to the IP concept.",
        success="The directory tower answers.",
        failure="Feedback links back to IP addresses.",
        explanation="DNS servers map names to IP addresses so you can use memorable names while machines use numbers.",
        reward="Relay Badge IV",
        mentor="Phone book analogy; mention what happens if DNS is wrong.",
        hints=["It's the thing you learned in level 3."],
    ),

    level(
        5, "Packets",
        objective="Understand that data travels in small pieces.",
        concepts=["packets", "headers", "reassembly"],
        story="A huge map cannot fit in one courier bag. The Relay cuts it into numbered pieces.",
        goal="Explain why data is split into packets.",
        learn=["Data is split into packets, each with a header (addresses, order number).", "Packets may take different routes; the receiver reassembles them."],
        example="Packet 1/3 -> Packet 2/3 -> Packet 3/3 -> rebuilt file",
        dialogue=["Big messages travel as many small pieces.", "Why bother splitting?"],
        challenge={
            "type": "mcq",
            "prompt": "Why is data split into packets?",
            "options": ["To make it slower", "So pieces can travel independently and be resent if lost", "Because cables are short", "To hide it from DNS"],
            "answer": 1,
            "wrong": "Think about what happens if one piece gets lost.",
        },
        reasoning="Reasoning about reliability and sharing paths.",
        success="The map is rebuilt at the destination.",
        failure="Feedback explains loss and resending.",
        explanation="Packets let many conversations share the same wires and let a lost piece be resent without resending everything.",
        reward="Relay Badge V",
        mentor="Explain headers and reassembly simply.",
        hints=["What if one bag falls off the drone?"],
    ),

    level(
        6, "Routing",
        objective="Understand how routers forward packets hop by hop.",
        prerequisites=["packets", "IP addresses"],
        concepts=["router", "hops", "routing tables"],
        story="Between towers stand routers, each knowing only the next best hop.",
        goal="Describe what a router does with a packet.",
        learn=["A router reads the destination IP and forwards the packet to the next hop.", "No router knows the whole path - just the next step."],
        example="You -> router A -> router B -> router C -> server (each is a hop)",
        dialogue=["Routers are signposts. Each points to the next.", "What does a router do?"],
        challenge={
            "type": "mcq",
            "prompt": "What does a router do with a packet?",
            "options": ["Reads the destination address and forwards it toward the next hop", "Opens and edits the message", "Stores it forever", "Converts it into DNS"],
            "answer": 0,
            "wrong": "Routers forward; they do not read your content or keep it.",
        },
        reasoning="Hop-by-hop forwarding model.",
        success="The packet reaches the far tower.",
        failure="Feedback restates forwarding.",
        explanation="Routers use the destination IP and a routing table to pick the next hop. Many hops later, the packet arrives.",
        reward="Relay Badge VI",
        mentor="Use road-sign analogy; mention traceroute as a tool.",
        hints=["Signposts don't read your letters."],
    ),

    level(
        7, "Ports",
        objective="Know that ports identify services on a device.",
        prerequisites=["IP addresses"],
        concepts=["port", "443", "80", "22"],
        story="One tower runs many services. Each has a numbered door.",
        goal="Give the standard port for secure web traffic (HTTPS).",
        learn=["An IP finds the device; a port finds the service on it.", "Common: 80 = HTTP, 443 = HTTPS, 22 = SSH."],
        example="203.0.113.7:443  -> the HTTPS door on that server",
        dialogue=["Address finds the building. Port finds the door.", "Which door number is secure web?"],
        challenge={
            "type": "text_answer",
            "prompt": "Standard port number for HTTPS?",
            "placeholder": "number",
            "accepted": ["443"],
            "wrong": "80 is plain HTTP. The secure one is different.",
        },
        reasoning="Distinguishing device address from service door.",
        success="The secure door opens.",
        failure="Feedback lists common ports.",
        explanation="HTTPS uses port 443 by default; HTTP uses 80. Firewalls often work with these numbers.",
        reward="Relay Badge VII",
        mentor="Explain ports as doors; connect to firewalls from the Watchtower.",
        hints=["It's a three-digit number starting with 4."],
    ),

    level(
        8, "HTTP",
        objective="Recognise a basic HTTP request and the GET method.",
        prerequisites=["clients and servers", "ports"],
        concepts=["HTTP", "GET", "POST", "status codes"],
        story="A courier's request slip is written in HTTP.",
        goal="Name the HTTP method that fetches a page.",
        learn=["HTTP is the language browsers and servers speak.", "GET asks for a page. POST sends data (like a login form).", "Status codes: 200 OK, 404 Not Found."],
        example="GET /profile HTTP/1.1\nHost: academy.example\n\n-> 200 OK",
        dialogue=["The request slip says which METHOD it uses.", "To fetch a page, the method is..."],
        challenge={
            "type": "text_answer",
            "prompt": "Which HTTP method asks a server to send a page?",
            "placeholder": "method name",
            "accepted": ["get"],
            "wrong": "POST sends data. Fetching uses the other common method.",
        },
        reasoning="Method semantics.",
        success="The page is delivered with 200 OK.",
        failure="Feedback contrasts GET and POST.",
        explanation="GET retrieves; POST submits. This app uses GET for pages and POST for login, quiz and mentor requests.",
        reward="Relay Badge VIII",
        mentor="Point at the Flask routes' methods=[...] as real examples.",
        hints=["Three letters."],
    ),

    level(
        9, "HTTPS",
        objective="Explain what HTTPS adds over HTTP.",
        prerequisites=["HTTP"],
        concepts=["encryption", "TLS", "certificates", "padlock"],
        story="A courier's slip can be read by anyone at each hop. The Relay offers sealed envelopes.",
        goal="State what HTTPS protects.",
        learn=["HTTPS = HTTP inside an encrypted tunnel (TLS).", "It stops eavesdropping and tampering, and proves you reached the real site (certificate)."],
        example="http://  -> readable by every hop\nhttps:// -> sealed; only you and the server can read it",
        dialogue=["Anyone on the path can read plain HTTP.", "What does the S in HTTPS give you?"],
        challenge={
            "type": "mcq",
            "prompt": "What does HTTPS add?",
            "options": ["Faster images", "Encryption and proof you reached the real server", "Free hosting", "Bigger packets"],
            "answer": 1,
            "wrong": "Think: sealed envelope + ID check.",
        },
        reasoning="Confidentiality + authenticity.",
        success="Sealed envelopes ship.",
        failure="Feedback restates the two benefits.",
        explanation="TLS encrypts traffic and uses certificates to verify the server. Never enter passwords on plain http://.",
        reward="Relay Badge IX",
        mentor="Explain the padlock and why login pages must be HTTPS.",
        hints=["S is for secure."],
    ),

    level(
        10, "Trace a Connection",
        objective="Put the whole journey in order and catch the wrong step.",
        prerequisites=["all Relay levels"],
        concepts=["end-to-end flow"],
        story="NULL scrambled the Relay's routing manual. One step is wrong.",
        goal="Find the incorrect step in the connection trace.",
        learn=["Type name -> DNS finds IP -> packets routed hop by hop -> port 443 -> HTTPS request -> response."],
        example="name -> DNS -> IP -> routers -> port -> HTTPS -> page",
        dialogue=["One step in the manual is a lie.", "Trace it from typing the name to seeing the page."],
        challenge={
            "type": "code_review",
            "label": "TRACE",
            "prompt": "Click the WRONG step, then choose why.",
            "code": [
                "1. You type academy.example in the browser",
                "2. DNS looks up the IP address for that name",
                "3. Your browser sends packets to the IP on port 443",
                "4. Routers open each packet and rewrite your message",
                "5. The server answers with HTTPS and the page appears",
            ],
            "target_line": 4,
            "why_options": [
                "Routers forward packets by address; they do not open or rewrite the content",
                "DNS should come after the server answers",
                "Port 443 does not exist",
                "Browsers cannot send packets",
            ],
            "why_answer": 0,
            "fixed": ["4. Routers read the destination IP and forward the packet to the next hop."],
        },
        reasoning="Integrating routing, ports, DNS, HTTPS.",
        success="The manual is repaired; the Relay hums.",
        failure="Feedback: which step contradicts what routers do?",
        explanation="Routers forward based on the IP header; with HTTPS they could not read the content anyway.",
        reward="Relay Master Badge",
        mentor="Help the player retell the journey in their own words.",
        hints=["Recall level 6."],
        boss=True,
    ),
]
