"""
Python - The Grove.

Eleven sections, 23 levels, one story: the Grove's doors lead to a
hut in the forest depths, a trapdoor drops you into the sewer
(snakes, your first dagger), a white tube climbs into a lab full of
doctors and specimen tanks, and a big snake guards the way out.

Every level has a `lesson` shown before play. Challenges are checked
server-side (challenges.py). Feedback only says which line or blank
is wrong; each level has one nudge hint that costs a hint chip.
"""

from courses.common import level


# ---------------------------------------------------------
# MAPS  (40 x 12, see courses/common.py for the legend)
# ---------------------------------------------------------

FOREST_1 = [
    "........................................",
    "........................................",
    "........................................",
    "..LLL........LLL.............LLL........",
    ".LLLLL......LLLLL...........LLLLL.......",
    "..LTL........LTL.............LTL........",
    "...T..........T......I........T.........",
    "...T..........T.....###.......T....D....",
    "..PT..........T..N............T..C.D..X.",
    "########################################",
    "########################################",
    "########################################",
]

FOREST_2 = [
    "........................................",
    "........................................",
    "....LLL..........LLL....LLL.............",
    "...LLLLL........LLLLL..LLLLL............",
    "....LTL..........LTL....LTL.............",
    ".....T............T......T..............",
    ".....T............T......T.....I........",
    ".....T.....B......T..N...T....###..D....",
    "..P..T............T......T.......C.D..X.",
    "########################################",
    "########################################",
    "########################################",
]

RAVINE = [
    "........................................",
    "........................................",
    "........................................",
    "..LLL..............LLL..........LLL.....",
    ".LLLLL............LLLLL........LLLLL....",
    "..LTL..............LTL..........LTL.....",
    "...T................T............T......",
    "...T........B.......T.....I......T..D...",
    "..PT.....N..........T...###......TC.D.X.",
    "#############.....######################",
    "#############.....######################",
    "#############SSSSS######################",
]

HUT = [
    "........................................",
    "........................................",
    "..LLL...............WWWWWWWWWWWWWWWWWWW.",
    ".LLLLL..............W.................W.",
    "..LTL...............W.................W.",
    "...T................W.................W.",
    "...T................W.....Q.....V.....W.",
    "...T.....................###....V.....W.",
    "..PT.....B....N..........I......V..C..W.",
    "####################WWWWWWWWWWWWWDDWWWW#",
    "####################W............X....W#",
    "########################################",
]

SEWER_1 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W..P...WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W......WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W......WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W......WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W......WWWWWWWW.......WWWWW.......WWWWWW",
    "W.............V......UU............D...W",
    "W.....N.......V..........I.........D...W",
    "W.............V..s....s.....B.s..C.D..XW",
    "WWWWWWW~~~~~WWWWWWWWWWWWWWW~~~~~~WWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

SEWER_2 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWW.....WWWWWWWWWWWWWWWWW",
    "W........UU............................W",
    "W...N.........s..........WWW......I....W",
    "W.P.....B........WWW..........s..WWW.D.W",
    "W..........s..................s..C...DXW",
    "WWWWWWWWWWW....WWWWWWWWWWW....WWWWWWWWWW",
    "WWWWWWWWWWW~~~~WWWWWWWWWWW~~~~WWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

SEWER_3 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWW..........WWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWW..........WWWWWWWWWWWWWWWWWW",
    "W...........UU..............UU.........W",
    "W..N.......WWWW...I..........V.....UUU.W",
    "W.P.....s........WWWW.s......VB......D.W",
    "W..................s.........V...C...DXW",
    "WWWWWWWWW~~~WWWWWWWWWWWWW~~~~~WWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

SEWER_4 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWG...GWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWG...GWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWG...GWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWG...GWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWG...GWW",
    "W..........UU....................G...GWW",
    "W....N...........I...............G...GWW",
    "W.P........s....WWW...s....B...C.D...GWW",
    "W..............s..............s..D.X.GWW",
    "WWWWWWWWW~~~~WWWWWWWWWW~~~~WWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

LAB_1 = [
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "G......................................G",
    "G..P...................................G",
    "G......................................G",
    "G..........A..........GGG..............G",
    "G.........GGG..........................G",
    "G.....N.......n........h........I......G",
    "G........GG........K...........GGG...D.G",
    "G........A........GGG..A...n....B..C.DXG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
]

LAB_2 = [
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "G......................................G",
    "G..P...................................G",
    "G......................................G",
    "G........GGG...........................G",
    "G.............................A........G",
    "G.....N.........n....I.......GGG.......G",
    "G........h..........GGG....h.........D.G",
    "G...A..........K....A......n....B..C.DXG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
]

LAB_3 = [
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "G......................................G",
    "G..P...................................G",
    "G......................................G",
    "G......GGG.............................G",
    "G.............A.......GGG..............G",
    "G....N.......GGG.....n.........I.......G",
    "G..........h...........h......GGG....D.G",
    "G.........A.........K......n....B..C.DXG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
]

LAB_4 = [
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "G......................................G",
    "G..P...................................G",
    "G......................................G",
    "G.......A......A......A......A.........G",
    "G......GGG....GGG....GGG....GGG........G",
    "G....N...........................I.....G",
    "G.........s.........h......s.....GGG.D.G",
    "G..............K.............n..B..C.DXG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
]

LAB_5 = [
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "G......................................G",
    "G..P...................................G",
    "G......................................G",
    "G......................A...............G",
    "G.....................GGG.....A........G",
    "G....N.....I.................GGG.......G",
    "G.......h.GGG....s.......h....s......D.G",
    "G...A..........K.............n..B..C.DXG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
]

BOSS_ARENA = [
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "G......................................G",
    "G..P...................................G",
    "G......................................G",
    "G......GGG..........GGG................G",
    "G......................................G",
    "G....N.............A........A..........G",
    "G.......K...................M........D.G",
    "G..................................C.DXG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
]

LAB_DEEP = [
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "G......................................G",
    "G..P...................................G",
    "G......................................G",
    "G..........GGG.........A...............G",
    "G.....................GGG..............G",
    "G......N...........n..........I........G",
    "G............s...............GGGB....D.G",
    "G......K.................A.........C.DXG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
]


# ---------------------------------------------------------
# LAB DOCTORS (idle NPC lines, cycled per level)
# ---------------------------------------------------------

DOCTOR_LINES = [
    "Are you the new intern? You're... not on the list. Nobody is on the list.",
    "Please don't touch the snakes. They bite. And they know Python.",
    "This is a restricted wing. So was the last one. And the one before that.",
    "No badge? Then technically you're a rounding error. Carry on.",
    "If you see Dr. Vex, tell him the big one escaped again. Actually, don't.",
    "Candy is for staff. Fine. Take one. You look like you've met the snakes.",
    "I'd call security, but security is a snake now. Long story.",
    "Loops, loops, loops. That specimen never stops. We should have used a break.",
]


# ---------------------------------------------------------
# LEVELS
# ---------------------------------------------------------

PYTHON_LEVELS = [

    # ===================== OUTPUT =====================

    level(
        1, "Speak to the Machine",
        section="Output",
        objective="Use print() to make Python output exact text.",
        concepts=["print()", "strings"],
        lesson={
            "title": "print() - making Python talk",
            "points": [
                "A computer does exactly what it is told - nothing more, nothing less.",
                "print() is the command that makes Python output something.",
                "Text is called a string. A string always sits inside quotes: \"like this\".",
                "The parentheses hand the string to print: print(\"hello\").",
                "Capital letters matter. open and Open are different words to a machine.",
            ],
            "example": 'print("hello")\n# output: hello',
        },
        story="You wake up on the forest floor of the Grove. Green digits fade from your vision. A small drone hovers over you: 'Recruit! The sim loaded you here. Everything in the Grove listens to Python.'",
        goal="Make the terminal print the word open to unlock the stone door.",
        gameplay="Walk right, talk to BYTE (E), jump for the hint chip, use the terminal by the sealed door.",
        dialogue=[
            "You're awake! I'm BYTE, your guide in the Grove.",
            "The stone door ahead only opens when it hears the word open.",
            "print() makes the machine say something. Whatever is inside the quotes comes out.",
            "The terminal is by the door. You read the lesson - now try it.",
        ],
        challenge={
            "type": "python_lines",
            "prompt": "Write one line of Python that prints the word open.",
            "placeholder": "",
            "patterns": [{"regex": r"print\(\s*([\"'])open\1\s*\)"}],
        },
        reasoning="Recognise that print outputs text, that text needs quotes, and that the word must be exact.",
        success="The terminal prints open and the door slides apart.",
        failure="The door stays shut; the terminal only says which line failed.",
        explanation="print(\"open\") tells Python to output the text open. The quotes mark it as text and the parentheses hand it to print.",
        reward="Grove Badge I",
        mentor="Explain what print does and why quotes matter; never type the answer for the player.",
        hints=["What did BYTE say goes inside the quotes?"],
        map=FOREST_1,
        theme="forest",
        intro=True,
    ),

    level(
        2, "Deeper Into the Grove",
        section="Output",
        objective="Understand that Python runs lines top to bottom.",
        prerequisites=["print()"],
        concepts=["print()", "sequence", "order of statements"],
        lesson={
            "title": "One line after another",
            "points": [
                "A program is a list of instructions. Python runs them top to bottom.",
                "Three print() lines produce three lines of output, in the same order.",
                "Change the order of the lines and you change the order of the output.",
                "Recap: strings need quotes, print needs parentheses.",
            ],
            "example": 'print("one")\nprint("two")\n# output:\n# one\n# two',
        },
        story="The first door led deeper. The trees are taller here and the light is thinner. A carved sign stands by the path.",
        goal="Arrange the three print lines so the door hears the words in the right order.",
        gameplay="Read the sign, talk to BYTE, drag the code pieces into order at the terminal.",
        sign="THE DOOR LISTENS FOR THREE WORDS, IN ORDER: wake - up - recruit",
        dialogue=[
            "This door wants three words, one after another.",
            "Python reads code the way you read a page: top line first.",
            "The terminal has the pieces already. Put them in the right order.",
        ],
        challenge={
            "type": "order_code",
            "prompt": "Drag the lines into the order the sign describes.",
            "pieces": ['print("wake")', 'print("up")', 'print("recruit")'],
            "shuffle": [1, 2, 0],
        },
        reasoning="Map the sign's order onto the order of statements.",
        success="Three words echo through the trees and the door opens.",
        failure="The terminal reports that the order isn't right.",
        explanation="Statements run in order. The top print runs first, so the order of lines is the order of output.",
        reward="Grove Badge II",
        mentor="Ask the player what runs first and why.",
        hints=["Which word did the sign list first?"],
        map=FOREST_2,
        theme="forest",
    ),

    # ===================== VARIABLES =====================

    level(
        3, "Variables",
        section="Variables",
        objective="Store a value under a name and print it.",
        prerequisites=["print()"],
        concepts=["variables", "assignment =", "printing a variable"],
        lesson={
            "title": "Variables - boxes with labels",
            "points": [
                "A variable is a labelled box that remembers a value.",
                "You make one with a name, an equals sign, and a value: code = 4172",
                "The name goes on the left of =, the value on the right.",
                "print(code) prints what is INSIDE the box. No quotes.",
                "print(\"code\") would print the letters c-o-d-e, because quotes make it text.",
            ],
            "example": "score = 10\nprint(score)\n# output: 10",
        },
        story="A ravine cuts the path in two. On the far side a gate keypad blinks. A wooden sign shows today's code.",
        goal="Store the gate code in a variable named code, then print the variable.",
        gameplay="Read the sign, jump the ravine, use the keypad terminal and fill the blanks.",
        sign="GATE CODE: 4172",
        dialogue=[
            "The keypad wants the code from the sign - but stored in a variable first.",
            "A variable is a box with a label. Put the number in, then print the box.",
            "Careful with quotes. The keypad wants the value, not the name.",
        ],
        challenge={
            "type": "fill_blank",
            "prompt": "Fill both blanks. Store the sign's code in code, then print the variable.",
            "code": ["code = ___", "print(___)"],
            "answers": [["4172"], ["code"]],
            "bank": ["4172", "code", "\"code\"", "\"4172\""],
        },
        reasoning="Separate storing a value from using it; understand that quotes turn a name into text.",
        success="The keypad prints 4172 and the gate opens.",
        failure="The keypad flashes and names the blank that is wrong.",
        explanation="code = 4172 stores the number under the name code. print(code) looks inside the box. print(\"code\") would print text.",
        reward="Grove Badge III",
        mentor="Explain variables as labelled boxes; contrast print(code) with print(\"code\") without giving the blanks.",
        hints=["One blank wants the number. The other wants the name of the box."],
        map=RAVINE,
        theme="forest",
    ),

    level(
        4, "The Hut",
        section="Variables",
        objective="Store text in a variable and use it to open the trapdoor.",
        prerequisites=["variables", "strings"],
        concepts=["string variables", "using a variable", "sequence"],
        lesson={
            "title": "Variables can hold text too",
            "points": [
                "A box can hold text as well as numbers: word = \"descend\"",
                "The quotes go around the VALUE, never around the variable name.",
                "Once stored, use the name anywhere: print(word) outputs descend.",
                "Two lines, in order: first store, then use. You cannot use a box before it exists.",
                "New in the world: press F to use whatever is in your selected slot (1-5).",
            ],
            "example": 'greeting = "hi"\nprint(greeting)\n# output: hi',
        },
        story="The path ends at a hut in the forest depths. A note is nailed to a post outside. Inside, something glints on a shelf, and the back room is choked with vines.",
        goal="Read the note, grab the dagger, cut the vines, then program the trapdoor terminal.",
        gameplay="Sign outside, dagger on the shelf (walk into it), select it with 1-5 and press F next to the vines, then use the terminal.",
        sign="NOTE: the trapdoor listens for the word descend. Store it in a variable called word, then print the variable.",
        dialogue=[
            "That glint on the shelf is a dagger. Walk into it to pick it up.",
            "Select it with its slot number, then press F to swing. Vines don't stand a chance.",
            "The trapdoor terminal wants the word from the note - stored first, printed second.",
        ],
        challenge={
            "type": "python_lines",
            "prompt": "Line 1: store the note's word in a variable called word. Line 2: print the variable.",
            "placeholder": "",
            "patterns": [
                {"regex": r"word\s*=\s*([\"'])descend\1"},
                {"regex": r"print\(\s*word\s*\)"},
            ],
        },
        reasoning="Apply assignment to a string and print the variable, not the name.",
        success="The trapdoor swings open and you drop into the dark.",
        failure="The terminal only reports which line is wrong.",
        explanation="word = \"descend\" stores text. print(word) outputs it. Quotes belong around the text, not around word.",
        reward="Grove Badge IV + Dagger",
        mentor="Reinforce quotes-around-values; ask what print(\"word\") would show.",
        hints=["Read the note again: which part is the name, which is the value?"],
        map=HUT,
        theme="forest",
    ),

    level(
        5, "Checkpoint: Output & Variables",
        kind="quiz",
        section="Variables",
        objective="Prove you remember print and variables before moving on.",
        concepts=["print()", "variables", "sequence"],
        lesson={
            "title": "Checkpoint - Output & Variables",
            "points": ["print() outputs text; text sits inside quotes.", "Lines run top to bottom.", "name = value stores; print(name) reads the box - no quotes.", "Quotes around a name print the letters of the name, not the value."],
            "example": 'code = 4172\nprint(code)   # 4172\nprint("code") # code',
        },
        story="BYTE blocks the path with a drill. 'Quick check before the next zone. Four questions. No terminal - just you.'",
        goal="Answer every question correctly to unlock the next level.",
        gameplay="Read the recap, then answer four questions. One or two reach back to earlier sections.",
        dialogue=["Checkpoint drill. Answer all four and the path opens."],
        challenge={
            "type": "quiz",
            "prompt": "Answer all four questions. You can retry as often as you like.",
            "questions": [
                {"prompt": "What does print(\"hi\") output?", "options": ["print", "hi", "\"hi\"", "nothing"], "answer": 1},
                {"prompt": "After code = 4172, what does print(code) show?", "options": ["code", "\"code\"", "4172", "an error"], "answer": 2},
                {"prompt": "Earlier section: two print lines, one above the other. Which runs first?", "options": ["The bottom one", "Both at the same time", "Python picks randomly", "The top one"], "answer": 3},
                {"prompt": "After code = 4172, what does print(\"code\") show?", "options": ["4172", "code", "an error", "nothing"], "answer": 1}
            ],
        },
        reasoning="Retrieval practice on the latest section, plus one or two cumulative questions.",
        success="All four correct - the path opens.",
        failure="The drill says which question is wrong, nothing more.",
        explanation="print outputs; quotes mark text; = stores; a name without quotes reads the stored value.",
        reward="Checkpoint Pin I",
        mentor="Coach with questions; never state the answer.",
        hints=["Re-read the lesson notes of the levels in this section."],
        theme="forest",
    ),

    # ===================== DATA TYPES =====================

    level(
        6, "Into the Sewer",
        section="Data Types",
        start_items=["DAGGER"],
        objective="Tell numbers and text apart.",
        prerequisites=["variables"],
        concepts=["int", "str", "types"],
        lesson={
            "title": "Types - numbers vs text",
            "points": [
                "Every value has a type. 3 is an int (a whole number). \"3\" is a str (text).",
                "Quotes are the giveaway: quotes = text, no quotes = number.",
                "You can only do maths with numbers. \"3\" + 1 is an error.",
                "type(3) tells you int. type(\"3\") tells you str.",
                "Danger below: snakes hurt on touch. Hearts are your health. Swing the dagger (F) at them.",
            ],
            "example": 'count = 3      # int\nlabel = "3"    # str\nprint(count + 1)   # 4',
        },
        story="You land in a sewer. Vines block the tunnel and something hisses in the dark. A sluice gate at the end has jammed - someone fed its counter text instead of a number.",
        goal="Cut through the vines, deal with the snakes, and give the sluice counter a real number.",
        gameplay="Dagger through the vines, fight or jump past the snakes, read the counter log, fix the blank.",
        sign="SLUICE COUNTER LOG: expected the number 3. Received \"3\" (text). Cannot add text. ERROR.",
        dialogue=[
            "Snakes. Keep your dagger selected and swing with F. Or jump over them, if you're quick.",
            "The sluice counter choked on text. Numbers never wear quotes.",
        ],
        challenge={
            "type": "fill_blank",
            "prompt": "Give the counter the NUMBER three.",
            "code": ["count = ___"],
            "answers": [["3"]],
            "bank": ["3", "\"3\"", "three", "3.0"],
        },
        reasoning="Recognise that quotes change the type and that the counter needs an int.",
        success="The counter reads 3 and the sluice opens.",
        failure="The counter errors and says the blank is wrong.",
        explanation="\"3\" is a string; 3 is an integer. Only the integer can be counted with.",
        reward="Grove Badge V",
        mentor="Explain int vs str; ask what the quotes do.",
        hints=["Look at what is wrapped around the 3 in the log."],
        map=SEWER_1,
        theme="sewer",
    ),

    level(
        7, "Sewer Junction",
        section="Data Types",
        start_items=["DAGGER"],
        objective="Use booleans and numbers in the right places.",
        prerequisites=["types"],
        concepts=["bool", "True / False", "int", "str"],
        lesson={
            "title": "The third type - True and False",
            "points": [
                "A bool is a yes/no value. It is written True or False - capital letter, no quotes.",
                "\"True\" with quotes is text, not a boolean.",
                "Bools answer questions: is the gate open? Is the depth safe?",
                "Recap: int for whole numbers, str for text, bool for yes/no.",
                "Cumulative: this junction wants one bool and one int.",
            ],
            "example": "gate_open = True\ndepth = 12\nlabel = \"north\"",
        },
        story="The tunnel forks at a junction with two flooded pits. The junction log expects a boolean and a number, and NULL has scrambled both.",
        goal="Set gate_open to a boolean and depth to a number.",
        gameplay="Jump the pits, clear the snakes, read the log, fill both blanks.",
        sign="JUNCTION LOG: gate_open must be the boolean yes. depth must be the number twelve.",
        dialogue=[
            "Two blanks. One wants a yes/no value, the other wants a count.",
            "Remember what quotes do to a value.",
        ],
        challenge={
            "type": "fill_blank",
            "prompt": "Fill the blanks with the right TYPES.",
            "code": ["gate_open = ___", "depth = ___"],
            "answers": [["True"], ["12"]],
            "bank": ["True", "\"True\"", "12", "\"12\"", "true"],
        },
        reasoning="Choose the correct literal form for a bool and an int.",
        success="The junction gate lifts.",
        failure="The log names the blank that has the wrong type.",
        explanation="True is a bool (capital T, no quotes). 12 is an int. Both with quotes would be strings.",
        reward="Grove Badge VI",
        mentor="Explain bool literals; ask why true (lowercase) fails.",
        hints=["Python's yes/no values start with a capital letter."],
        map=SEWER_2,
        theme="sewer",
    ),

    # ===================== INPUT & OUTPUT =====================

    level(
        8, "The Guard Pipe",
        section="Input & Output",
        start_items=["DAGGER"],
        sign="GUARD PIPE: ask for a name, store it, greet with it. Two lines.",
        objective="Ask the user for text with input() and respond.",
        prerequisites=["variables", "strings"],
        concepts=["input()", "storing input", "joining strings with +"],
        lesson={
            "title": "input() - asking the user",
            "points": [
                "input(\"question \") pauses and waits for the user to type something.",
                "Whatever they type comes back as a string. Store it: name = input(\"Name? \")",
                "Join strings with +: \"Welcome, \" + name",
                "Pattern: ask -> store -> use. Three ideas you already know, chained.",
            ],
            "example": 'name = input("Who goes there? ")\nprint("Welcome, " + name)',
        },
        story="A guard pipe blocks the tunnel. Its old program asked every traveller for a name - until the snakes chewed the code.",
        goal="Rebuild the guard: ask for a name with input(), then greet the traveller by name.",
        gameplay="Cut the vines, pass the snakes, rewrite the guard's two lines.",
        dialogue=[
            "The guard pipe used to ASK a question and ANSWER with your name.",
            "input() asks and waits. Save what comes back, then use it in a print.",
        ],
        challenge={
            "type": "python_lines",
            "prompt": "Line 1: ask for a name with input() and store it in name. Line 2: print a greeting that uses name.",
            "placeholder": "",
            "patterns": [
                {"regex": r"name\s*=\s*input\(\s*([\"'][^\"']*[\"'])?\s*\)"},
                {"regex": r"print\(.*\bname\b.*\)"},
            ],
        },
        reasoning="Chain input, assignment and string joining.",
        success="The guard pipe greets you and swings aside.",
        failure="The terminal reports which line is wrong.",
        explanation="input() returns a string; storing it lets you reuse it; + joins two strings.",
        reward="Grove Badge VII",
        mentor="Explain that input returns a string; help with + without writing the lines.",
        hints=["Where does the answer to a question need to be stored before you can greet with it?"],
        map=SEWER_3,
        theme="sewer",
    ),

    level(
        9, "The White Tube",
        section="Input & Output",
        start_items=["DAGGER"],
        objective="Convert input text into a number before doing maths.",
        prerequisites=["input()", "types"],
        concepts=["int()", "type conversion", "input returns str"],
        lesson={
            "title": "input() gives text - convert it",
            "points": [
                "input() ALWAYS returns a string, even if the user types 12.",
                "int(\"12\") converts text to the number 12.",
                "So: ask -> convert -> use. age = int(age) replaces the text with a number.",
                "Only then can you do maths: age + 1",
                "Cumulative: input + variables + types, in the right ORDER.",
            ],
            "example": 'age = input("Age? ")\nage = int(age)\nprint(age + 1)',
        },
        story="The sewer ends at a gleaming white tube that drops down from somewhere above. Its hatch runs a tiny program - in the wrong order.",
        goal="Put the hatch program in the correct order so it can add one to a number.",
        gameplay="Reach the tube, use the hatch terminal, drag the lines into order.",
        sign="HATCH: ask for years, convert to a number, print one more.",
        dialogue=[
            "That tube goes UP into something very clean. Not sewer-clean. Lab-clean.",
            "The hatch program is scrambled. Think about what must happen before the maths.",
        ],
        challenge={
            "type": "order_code",
            "prompt": "Drag the lines into the order that works.",
            "pieces": ['age = input("Years in the Academy? ")', "age = int(age)", "print(age + 1)"],
            "shuffle": [2, 0, 1],
        },
        reasoning="Order operations: you cannot convert before you ask, or add before you convert.",
        success="The hatch hisses open. You climb into the tube.",
        failure="The hatch says the order isn't right.",
        explanation="input gives a string; int() converts; only then can + add numbers.",
        reward="Grove Badge VIII",
        mentor="Ask what type input returns and what happens if you add 1 to it.",
        hints=["Which line can't run until another line has happened?"],
        map=SEWER_4,
        theme="sewer",
    ),

    level(
        10, "Checkpoint: Types & Input",
        kind="quiz",
        section="Input & Output",
        objective="Prove you remember types, input and conversion before moving on.",
        concepts=["int", "str", "bool", "input()", "int()"],
        lesson={
            "title": "Checkpoint - Types & Input",
            "points": ["3 is an int, \"3\" is a str, True is a bool.", "input() always returns a string.", "int(\"12\") turns text into a number before maths.", "Earlier: variables hold any of these types."],
            "example": 'age = input("Age? ")   # "12" (text)\nage = int(age)         # 12 (number)',
        },
        story="BYTE blocks the path with a drill. 'Quick check before the next zone. Four questions. No terminal - just you.'",
        goal="Answer every question correctly to unlock the next level.",
        gameplay="Read the recap, then answer four questions. One or two reach back to earlier sections.",
        dialogue=["Checkpoint drill. Answer all four and the path opens."],
        challenge={
            "type": "quiz",
            "prompt": "Answer all four questions. You can retry as often as you like.",
            "questions": [
                {"prompt": "What is type(\"3\")?", "options": ["int", "bool", "str", "float"], "answer": 2},
                {"prompt": "What does input() return, no matter what the user types?", "options": ["A number", "A string", "True or False", "Nothing"], "answer": 1},
                {"prompt": "Which turns the text \"12\" into the number 12?", "options": ["str(12)", "print(12)", "\"12\" + 1", "int(\"12\")"], "answer": 3},
                {"prompt": "Earlier section: which line stores the text Ada in a variable called name?", "options": ["name = \"Ada\"", "\"name\" = Ada", "name == \"Ada\"", "print(name)"], "answer": 0}
            ],
        },
        reasoning="Retrieval practice on the latest section, plus one or two cumulative questions.",
        success="All four correct - the path opens.",
        failure="The drill says which question is wrong, nothing more.",
        explanation="Quotes make strings; input gives strings; int() converts; = stores.",
        reward="Checkpoint Pin II",
        mentor="Coach with questions; never state the answer.",
        hints=["Re-read the lesson notes of the levels in this section."],
        theme="sewer",
    ),

    # ===================== CONDITIONS =====================

    level(
        11, "The Lab",
        section="Conditions",
        start_items=["DAGGER"],
        objective="Use if to run code only when a condition is true.",
        prerequisites=["variables", "strings"],
        concepts=["if", "==", "indentation"],
        lesson={
            "title": "if - making decisions",
            "points": [
                "if condition: runs the indented lines only when the condition is True.",
                "== asks 'are these equal?'. One = stores, two == compares.",
                "The if line ends with a colon. The lines under it are indented by 4 spaces.",
                "Indentation is not decoration - it tells Python what belongs to the if.",
                "Lab rules: some doctors are harmless and chatty. Some are not. Candy (F) heals.",
            ],
            "example": 'if password == "grove":\n    print("open")',
        },
        story="The tube opens into a white, humming lab. Doctors in coats glance up - most go back to their clipboards; one does not. A keypad door bars the way and a password is taped beside it.",
        goal="Write the if that opens the door only for the taped password.",
        gameplay="Talk to the doctors (E), avoid or fight the hostile one, grab candy, read the sign, fill the blanks.",
        sign="PASSWORD: lab   (yes, someone taped the password next to the door. Note that for the Secure Coding course.)",
        npcs=DOCTOR_LINES,
        dialogue=[
            "Welcome to somebody's lab. Nobody here expected you.",
            "The keypad decides with an if. Two equals signs to compare, and mind the indent.",
        ],
        challenge={
            "type": "fill_blank",
            "prompt": "Fill the blanks so the door opens only when the password matches the sign.",
            "code": ["if password == ___:", "    print(___)"],
            "answers": [["\"lab\""], ["\"open\""]],
            "bank": ["\"lab\"", "lab", "\"open\"", "open", "=="],
        },
        reasoning="Compare against a string literal and print a string in the indented block.",
        success="The keypad door unlocks.",
        failure="The keypad names the blank that's wrong.",
        explanation="if password == \"lab\": compares text; the indented print runs only when it matches.",
        reward="Grove Badge IX",
        mentor="Explain = vs == and indentation; do not give the blanks.",
        hints=["Both blanks are text values. What do text values need?"],
        map=LAB_1,
        theme="lab",
    ),

    level(
        12, "Restricted Wing",
        section="Conditions",
        start_items=["DAGGER"],
        sign="SCANNER: red badges enter. Everyone else is denied.",
        objective="Use else to handle the other case.",
        prerequisites=["if"],
        concepts=["if / else", "two branches"],
        lesson={
            "title": "else - the other path",
            "points": [
                "if handles the yes case. else handles everything else.",
                "else has no condition of its own - it just ends with a colon.",
                "Both blocks are indented. Exactly one of them runs.",
                "Cumulative: variables (badge), strings, ==, and two indented blocks.",
            ],
            "example": 'if badge == "red":\n    print("enter")\nelse:\n    print("denied")',
        },
        story="A restricted wing. Two doctors here take their job seriously. The scanner should accept red badges and refuse everything else.",
        goal="Write the four-line if/else for the badge scanner.",
        gameplay="Survive the wing, use the scanner terminal, type four lines.",
        npcs=DOCTOR_LINES[2:] + DOCTOR_LINES[:2],
        dialogue=[
            "Red badge in, everyone else out. That's two outcomes.",
            "One if, one else, and both of them get an indented print.",
        ],
        challenge={
            "type": "python_lines",
            "prompt": "Four lines: if badge equals \"red\" print enter, else print denied.",
            "placeholder": "",
            "patterns": [
                {"regex": r"if\s+badge\s*==\s*([\"'])red\1\s*:"},
                {"regex": r"\s+print\(\s*([\"'])enter\1\s*\)"},
                {"regex": r"else\s*:"},
                {"regex": r"\s+print\(\s*([\"'])denied\1\s*\)"},
            ],
        },
        reasoning="Structure a two-branch decision with correct colons and indentation.",
        success="The scanner accepts and the wing opens.",
        failure="The terminal reports which of the four lines is wrong.",
        explanation="if tests the badge; else covers the rest; the indented prints belong to their branch.",
        reward="Grove Badge X",
        mentor="Ask which line runs when badge is blue.",
        hints=["Count the colons. Every block opener needs one."],
        map=LAB_2,
        theme="lab",
    ),

    level(
        13, "Access Levels",
        section="Conditions",
        start_items=["DAGGER"],
        sign="ACCESS: 3 = director, 2 = doctor, anyone else = visitor.",
        objective="Chain several conditions with elif.",
        prerequisites=["if / else"],
        concepts=["elif", "condition order"],
        lesson={
            "title": "elif - more than two options",
            "points": [
                "elif means 'else, if'. It adds another test between if and else.",
                "Python checks top to bottom and runs the FIRST branch that is true.",
                "Order: if, then any number of elif, then an optional else.",
                "Only one branch ever runs, even if several conditions would be true.",
            ],
            "example": 'if level == 3:\n    print("director")\nelif level == 2:\n    print("doctor")\nelse:\n    print("visitor")',
        },
        story="An access console sorts people by clearance level: 3 is a director, 2 is a doctor, anyone else is a visitor. Its lines are scattered.",
        goal="Rebuild the three-way decision in the right order.",
        gameplay="Cross the wing, use the console, drag six lines into place.",
        npcs=DOCTOR_LINES[4:] + DOCTOR_LINES[:4],
        dialogue=[
            "Three outcomes this time. if, elif, else - in that order.",
            "Each opener is followed by its own indented print.",
        ],
        challenge={
            "type": "order_code",
            "prompt": "Drag the lines into a working if / elif / else.",
            "pieces": [
                "if level == 3:",
                '    print("director")',
                "elif level == 2:",
                '    print("doctor")',
                "else:",
                '    print("visitor")',
            ],
            "shuffle": [4, 1, 0, 5, 2, 3],
        },
        reasoning="Pair each opener with its block and keep if -> elif -> else order.",
        success="The console sorts you as... visitor. The door opens anyway.",
        failure="The console says the order isn't right.",
        explanation="if starts the chain, elif adds tests, else ends it; each indented print follows its opener.",
        reward="Grove Badge XI",
        mentor="Ask what happens if else came first.",
        hints=["Which line must be first, and which can only be last?"],
        map=LAB_3,
        theme="lab",
    ),

    level(
        14, "Checkpoint: Conditions",
        kind="quiz",
        section="Conditions",
        objective="Prove you remember if, elif and else before moving on.",
        concepts=["if", "elif", "else", "=="],
        lesson={
            "title": "Checkpoint - Conditions",
            "points": ["== compares; = stores.", "if lines end with a colon; the block under it is indented.", "if / elif / else: Python runs the FIRST true branch only.", "Earlier: a bool (True/False) is what a condition produces."],
            "example": 'if level == 3:\n    print("director")\nelif level == 2:\n    print("doctor")\nelse:\n    print("visitor")',
        },
        story="BYTE blocks the path with a drill. 'Quick check before the next zone. Four questions. No terminal - just you.'",
        goal="Answer every question correctly to unlock the next level.",
        gameplay="Read the recap, then answer four questions. One or two reach back to earlier sections.",
        dialogue=["Checkpoint drill. Answer all four and the path opens."],
        challenge={
            "type": "quiz",
            "prompt": "Answer all four questions. You can retry as often as you like.",
            "questions": [
                {"prompt": "Which symbol asks whether two values are equal?", "options": ["=", ":", "==", "->"], "answer": 2},
                {"prompt": "In an if / elif / else chain, how many branches run?", "options": ["All the true ones", "Exactly one", "None", "Always the last"], "answer": 1},
                {"prompt": "What must every if line end with?", "options": ["A colon", "A semicolon", "A full stop", "Nothing"], "answer": 0},
                {"prompt": "Earlier section: gate_open = True. What type is gate_open?", "options": ["str", "int", "list", "bool"], "answer": 3}
            ],
        },
        reasoning="Retrieval practice on the latest section, plus one or two cumulative questions.",
        success="All four correct - the path opens.",
        failure="The drill says which question is wrong, nothing more.",
        explanation="== compares, colons open blocks, one branch runs, conditions are bools.",
        reward="Checkpoint Pin III",
        mentor="Coach with questions; never state the answer.",
        hints=["Re-read the lesson notes of the levels in this section."],
        theme="lab",
    ),

    # ===================== LOOPS =====================

    level(
        15, "The Tanks",
        section="Loops",
        start_items=["DAGGER"],
        objective="Repeat an action with a for loop.",
        prerequisites=["print()", "indentation"],
        concepts=["for", "range()", "loop body"],
        lesson={
            "title": "for - do it N times",
            "points": [
                "for i in range(5): repeats the indented block five times.",
                "range(5) counts 0, 1, 2, 3, 4 - five numbers.",
                "The indented lines are the loop body. They run once per number.",
                "A loop replaces copy-pasting the same line again and again.",
            ],
            "example": 'for i in range(3):\n    print("ring")\n# ring ring ring',
        },
        story="A hall of specimen tanks. Five of them. Each must be checked - and the checker prints once per tank.",
        goal="Loop over the five tanks and print checked for each.",
        gameplay="Pass the tanks and the loose snakes, read the sign, fill the blanks.",
        sign="5 TANKS. The checker must print checked once per tank.",
        npcs=DOCTOR_LINES[1:] + DOCTOR_LINES[:1],
        dialogue=[
            "Five tanks, one line of code. That's what loops are for.",
            "The number of repeats lives inside range().",
        ],
        challenge={
            "type": "fill_blank",
            "prompt": "Fill the blanks so the loop prints checked once per tank.",
            "code": ["for tank in range(___):", '    print(___)'],
            "answers": [["5"], ['"checked"']],
            "bank": ["5", "tank", '"checked"', "range", "4"],
        },
        reasoning="Connect the repeat count to range and the repeated action to the body.",
        success="Five checks print; the hall door opens.",
        failure="The checker names the wrong blank.",
        explanation="range(5) gives five numbers; the body prints once for each.",
        reward="Grove Badge XII",
        mentor="Ask what range(5) counts.",
        hints=["How many tanks did the sign count?"],
        map=LAB_4,
        theme="lab",
    ),

    level(
        16, "While It Breathes",
        section="Loops",
        start_items=["DAGGER"],
        objective="Repeat while a condition stays true.",
        prerequisites=["for", "conditions"],
        concepts=["while", "loop counter", "stopping condition"],
        lesson={
            "title": "while - repeat until something changes",
            "points": [
                "while condition: repeats the body as long as the condition is True.",
                "Something in the body must change the condition, or the loop never ends.",
                "Classic pattern: count = 0, while count < 3, count = count + 1 inside.",
                "Cumulative: variables, comparisons and indentation all at once.",
            ],
            "example": "count = 0\nwhile count < 3:\n    print(\"hiss\")\n    count = count + 1",
        },
        story="A monitor loops a recording of a specimen: it hisses exactly three times and stops. The doctors want the code that produced it.",
        goal="Complete the while loop so it hisses three times and stops.",
        gameplay="Get past the doctors, read the sign, fill two blanks.",
        sign="RECORDING: hiss, hiss, hiss - then silence. The counter grows by one each time.",
        npcs=DOCTOR_LINES[7:] + DOCTOR_LINES[:7],
        dialogue=[
            "A while loop keeps going until its condition turns False.",
            "If the counter never grows, the hissing never stops. Ask me how I know.",
        ],
        challenge={
            "type": "fill_blank",
            "prompt": "Fill the blanks so the loop prints hiss three times, then stops.",
            "code": ["count = 0", "while count < ___:", '    print("hiss")', "    count = count + ___"],
            "answers": [["3"], ["1"]],
            "bank": ["3", "1", "0", "count"],
        },
        reasoning="Relate the stopping condition to the counter's growth.",
        success="Three hisses, then silence. The door opens.",
        failure="The monitor names the wrong blank.",
        explanation="count grows by 1 each pass; when it reaches 3 the condition fails and the loop stops.",
        reward="Grove Badge XIII",
        mentor="Ask the player to count passes by hand.",
        hints=["How much does the counter grow each time, and where must it stop?"],
        map=LAB_5,
        theme="lab",
    ),

    level(
        17, "The Big Snake",
        section="Loops",
        start_items=["DAGGER"],
        objective="Combine a loop with an if inside it.",
        prerequisites=["for", "if / else"],
        concepts=["nesting", "loop with a condition inside"],
        lesson={
            "title": "A loop with a decision inside",
            "points": [
                "Blocks can nest: an if inside a for is indented twice.",
                "The outer loop repeats; the inner if decides each time.",
                "The big snake is a loop: it charges, fires, then rests. Attack while it rests.",
                "Fireballs come low or high. Jump the low ones. Stay down for the high ones.",
                "Cumulative: for + range + if/else + print.",
            ],
            "example": 'for fireball in range(3):\n    if dodged:\n        print("safe")\n    else:\n        print("hit")',
        },
        story="The end of the wing is a tank the size of a room, and the tank is empty. The big snake is out. It charges, spits fire in a loop, and rests - then starts again.",
        goal="Defeat the big snake by striking during its rest, then order the loop that describes the fight.",
        gameplay="Dodge the volley (jump low fireballs), hit the snake while it shows VULNERABLE, repeat until it falls. Then use the console.",
        npcs=[],
        dialogue=[
            "That's the specimen. It loops: charge, fire, rest. It's only soft while it rests.",
            "Watch the height of each fireball. Jump the low ones. Duck nothing - just don't jump for the high ones.",
        ],
        challenge={
            "type": "order_code",
            "prompt": "The snake is down. Drag the lines into a loop that checks each fireball.",
            "pieces": [
                "for fireball in range(3):",
                "    if dodged:",
                '        print("safe")',
                "    else:",
                '        print("hit")',
            ],
            "shuffle": [3, 0, 4, 1, 2],
        },
        reasoning="Nest a two-branch decision inside a repeat and keep the indentation consistent.",
        success="The console logs the fight. The way out of the wing opens.",
        failure="The console says the order isn't right.",
        explanation="The for runs three times; each time the if/else picks a branch; the double indent shows what belongs to what.",
        reward="Grove Badge XIV + Serpent Scale",
        mentor="Ask which line is indented twice and why.",
        hints=["The loop line opens everything. What must come directly under it?"],
        map=BOSS_ARENA,
        theme="lab",
        boss=True,
    ),

    level(
        18, "Checkpoint: Loops",
        kind="quiz",
        section="Loops",
        objective="Prove you remember for and while loops before moving on.",
        concepts=["for", "range()", "while", "nesting"],
        lesson={
            "title": "Checkpoint - Loops",
            "points": ["for i in range(n): repeats n times; range(4) is 0,1,2,3.", "while repeats until its condition is False - something inside must change it.", "An if inside a loop is indented one level deeper.", "Earlier: count = count + 1 grows a variable by one."],
            "example": 'count = 0\nwhile count < 3:\n    print("hiss")\n    count = count + 1',
        },
        story="BYTE blocks the path with a drill. 'Quick check before the next zone. Four questions. No terminal - just you.'",
        goal="Answer every question correctly to unlock the next level.",
        gameplay="Read the recap, then answer four questions. One or two reach back to earlier sections.",
        dialogue=["Checkpoint drill. Answer all four and the path opens."],
        challenge={
            "type": "quiz",
            "prompt": "Answer all four questions. You can retry as often as you like.",
            "questions": [
                {"prompt": "What numbers does range(4) produce?", "options": ["1, 2, 3, 4", "0, 1, 2, 3, 4", "0, 1, 2, 3", "4"], "answer": 2},
                {"prompt": "When does a while loop stop?", "options": ["After ten passes", "When its condition becomes False", "When print runs", "It never stops"], "answer": 1},
                {"prompt": "Earlier section: inside a for loop, an if line is indented...", "options": ["Not at all", "The same as the for", "One level deeper than the for", "Two levels deeper"], "answer": 2},
                {"prompt": "Earlier section: what does count = count + 1 do?", "options": ["Compares count with 1", "Prints count", "Adds one to count", "Starts a loop"], "answer": 2}
            ],
        },
        reasoning="Retrieval practice on the latest section, plus one or two cumulative questions.",
        success="All four correct - the path opens.",
        failure="The drill says which question is wrong, nothing more.",
        explanation="range counts from 0; while needs its condition to change; nesting is shown by indentation.",
        reward="Checkpoint Pin IV",
        mentor="Coach with questions; never state the answer.",
        hints=["Re-read the lesson notes of the levels in this section."],
        theme="lab",
    ),

    # ===================== LISTS =====================

    level(
        19, "Specimen List",
        section="Lists",
        start_items=["DAGGER"],
        objective="Read an item from a list by its index.",
        prerequisites=["variables", "strings"],
        concepts=["list", "index", "zero-based"],
        lesson={
            "title": "Lists - many values in one box",
            "points": [
                "A list holds several values in order: specimens = [\"viper\", \"cobra\", \"python\"]",
                "Each value has a position called an index. Counting starts at 0.",
                "specimens[0] is \"viper\". specimens[2] is the THIRD item.",
                "Square brackets make the list and also look inside it.",
            ],
            "example": 'keys = ["red", "blue", "green"]\nprint(keys[1])   # blue',
        },
        story="Deeper in the lab, the records room. A list of specimens is pinned up and the console wants the third one - but Python counts from zero.",
        goal="Print the third specimen from the list.",
        gameplay="Reach the console, read the sign, fill the index.",
        sign="RECORDS: print the THIRD specimen. Remember how Python counts.",
        npcs=DOCTOR_LINES[3:] + DOCTOR_LINES[:3],
        dialogue=[
            "Lists keep things in order, and the first slot is number zero.",
            "The console wants the third one. Count carefully.",
        ],
        challenge={
            "type": "fill_blank",
            "prompt": "Fill the index so the third specimen prints.",
            "code": ['specimens = ["viper", "cobra", "python"]', "print(specimens[___])"],
            "answers": [["2"]],
            "bank": ["2", "3", "1", "0"],
        },
        reasoning="Translate 'third' into a zero-based index.",
        success="python prints. The records door opens.",
        failure="The console names the wrong blank.",
        explanation="Index 0 is viper, 1 is cobra, 2 is python - the third item.",
        reward="Grove Badge XV",
        mentor="Ask the player to number the items starting from zero.",
        hints=["What number is the FIRST item?"],
        map=LAB_DEEP,
        theme="lab",
    ),

    level(
        20, "Adding to the List",
        section="Lists",
        start_items=["DAGGER"],
        sign="INTAKE: build the list, add the new specimen, then print each name.",
        objective="Add to a list and loop over it.",
        prerequisites=["lists", "for"],
        concepts=["append()", "for item in list"],
        lesson={
            "title": "Growing a list and walking through it",
            "points": [
                "specimens.append(\"adder\") adds a value to the END of the list.",
                "for name in specimens: visits every item, one per pass.",
                "Inside the loop, name holds the current item.",
                "Cumulative: lists + for loops. Order matters: build, add, then loop.",
            ],
            "example": 'keys = ["red"]\nkeys.append("blue")\nfor k in keys:\n    print(k)',
        },
        story="A new specimen arrived and the intake program must add it, then read the whole list back.",
        goal="Order the lines: make the list, append the new one, loop and print each.",
        gameplay="Use the intake console and drag four lines into order.",
        npcs=DOCTOR_LINES[5:] + DOCTOR_LINES[:5],
        dialogue=[
            "Build the list, add to it, then walk through it. Three steps, in order.",
        ],
        challenge={
            "type": "order_code",
            "prompt": "Drag the lines so the program builds, adds, then prints every specimen.",
            "pieces": [
                'specimens = ["viper", "cobra"]',
                'specimens.append("adder")',
                "for name in specimens:",
                "    print(name)",
            ],
            "shuffle": [2, 0, 3, 1],
        },
        reasoning="Sequence creation, mutation and iteration; keep the loop body under the loop.",
        success="Three names print. The intake door opens.",
        failure="The console says the order isn't right.",
        explanation="The list must exist before append; the loop body must follow the for line.",
        reward="Grove Badge XVI",
        mentor="Ask what the loop prints if append came after it.",
        hints=["Can you add to a list that doesn't exist yet?"],
        map=LAB_DEEP,
        theme="lab",
    ),

    # ===================== DICTIONARIES =====================

    level(
        21, "Lab Records",
        section="Dictionaries",
        start_items=["DAGGER"],
        objective="Look up a value by its key.",
        prerequisites=["lists", "strings"],
        concepts=["dict", "key: value", "lookup"],
        lesson={
            "title": "Dictionaries - labelled drawers",
            "points": [
                "A dictionary pairs keys with values: doors = {\"north\": \"locked\", \"east\": \"open\"}",
                "Look up by key, not by position: doors[\"east\"] gives \"open\".",
                "Keys are usually strings, so they need quotes.",
                "Lists use numbers to find things; dictionaries use names.",
            ],
            "example": 'doors = {"north": "locked", "east": "open"}\nprint(doors["north"])   # locked',
        },
        story="A wall map lists every door in the wing with its state. The console needs the east door's status.",
        goal="Print the value stored under the key east.",
        gameplay="Reach the console and fill the key.",
        sign="MAP: north is locked, east is open. The console wants EAST.",
        npcs=DOCTOR_LINES[6:] + DOCTOR_LINES[:6],
        dialogue=[
            "Dictionaries don't count. They label. Ask for the drawer by name.",
        ],
        challenge={
            "type": "fill_blank",
            "prompt": "Fill the key so the east door's status prints.",
            "code": ['doors = {"north": "locked", "east": "open"}', "print(doors[___])"],
            "answers": [['"east"']],
            "bank": ['"east"', "east", "1", '"open"'],
        },
        reasoning="Use a quoted key for lookup rather than an index or the value.",
        success="open prints; the map room unlocks.",
        failure="The console names the wrong blank.",
        explanation="doors[\"east\"] returns the value paired with the key east.",
        reward="Grove Badge XVII",
        mentor="Contrast list indexes with dictionary keys.",
        hints=["Is the key a name or a number? What do names need?"],
        map=LAB_DEEP,
        theme="lab",
    ),

    level(
        22, "Update the Record",
        section="Dictionaries",
        start_items=["DAGGER"],
        sign="MAINTENANCE: the north door is now open. Update the record and read it back.",
        objective="Change a value in a dictionary and read it back.",
        prerequisites=["dict lookup"],
        concepts=["assignment into a dict", "reading after writing"],
        lesson={
            "title": "Changing a drawer's contents",
            "points": [
                "doors[\"north\"] = \"open\" puts a new value in the drawer labelled north.",
                "Reading it afterwards gives the new value.",
                "Same square brackets for reading and writing - the = makes it a write.",
                "Cumulative: dictionaries + assignment + print.",
            ],
            "example": 'doors["north"] = "open"\nprint(doors["north"])   # open',
        },
        story="Maintenance unlocked the north door but never updated the map. Fix the record, then confirm it.",
        goal="Set the north door to open in the dictionary, then print its new value.",
        gameplay="Use the map console and type two lines.",
        npcs=DOCTOR_LINES[2:] + DOCTOR_LINES[:2],
        dialogue=[
            "Write into the drawer, then read it back to prove it changed.",
        ],
        challenge={
            "type": "python_lines",
            "prompt": "Line 1: set doors[\"north\"] to \"open\". Line 2: print doors[\"north\"].",
            "placeholder": "",
            "patterns": [
                {"regex": r"doors\[\s*([\"'])north\1\s*\]\s*=\s*([\"'])open\2"},
                {"regex": r"print\(\s*doors\[\s*([\"'])north\1\s*\]\s*\)"},
            ],
        },
        reasoning="Write then read the same key.",
        success="The map now says open. The door agrees.",
        failure="The terminal reports which line is wrong.",
        explanation="Assigning to doors[\"north\"] replaces the value; printing the same key shows the change.",
        reward="Grove Badge XVIII",
        mentor="Ask what the print would show if line 1 were missing.",
        hints=["Reading and writing use the same brackets. What makes one of them a write?"],
        map=LAB_DEEP,
        theme="lab",
    ),

    level(
        23, "Checkpoint: Lists & Dictionaries",
        kind="quiz",
        section="Dictionaries",
        objective="Prove you remember lists and dictionaries before moving on.",
        concepts=["list", "index", "append()", "dict", "key"],
        lesson={
            "title": "Checkpoint - Lists & Dictionaries",
            "points": ["Lists keep order; the first index is 0.", "append() adds to the end.", "Dictionaries look values up by key: doors[\"east\"].", "Earlier: for item in items: visits each item once."],
            "example": 'items = ["a", "b"]\nitems.append("c")\ndoors = {"east": "open"}\nprint(doors["east"])',
        },
        story="BYTE blocks the path with a drill. 'Quick check before the next zone. Four questions. No terminal - just you.'",
        goal="Answer every question correctly to unlock the next level.",
        gameplay="Read the recap, then answer four questions. One or two reach back to earlier sections.",
        dialogue=["Checkpoint drill. Answer all four and the path opens."],
        challenge={
            "type": "quiz",
            "prompt": "Answer all four questions. You can retry as often as you like.",
            "questions": [
                {"prompt": "items = [\"a\", \"b\", \"c\"]. What is items[0]?", "options": ["\"b\"", "\"a\"", "\"c\"", "an error"], "answer": 1},
                {"prompt": "doors[\"east\"] finds a value by its...", "options": ["position", "key", "length", "type"], "answer": 1},
                {"prompt": "What does items.append(\"d\") do?", "options": ["Removes an item", "Sorts the list", "Prints the list", "Adds \"d\" to the end"], "answer": 3},
                {"prompt": "Earlier section: how many times does the body of for x in items: run?", "options": ["Once", "Once per item", "Until False", "Always three times"], "answer": 1}
            ],
        },
        reasoning="Retrieval practice on the latest section, plus one or two cumulative questions.",
        success="All four correct - the path opens.",
        failure="The drill says which question is wrong, nothing more.",
        explanation="Indexes start at 0, append adds at the end, dictionaries use keys, loops visit each item.",
        reward="Checkpoint Pin V",
        mentor="Coach with questions; never state the answer.",
        hints=["Re-read the lesson notes of the levels in this section."],
        theme="lab",
    ),

    # ===================== FUNCTIONS =====================

    level(
        24, "Reusable Spell",
        section="Functions",
        start_items=["DAGGER"],
        sign="CONSOLE: define unlock so it prints unlocked, then call it.",
        objective="Define a function and call it.",
        prerequisites=["print()", "indentation"],
        concepts=["def", "function body", "calling"],
        lesson={
            "title": "Functions - name a block, reuse it",
            "points": [
                "def unlock(): creates a function - a block of code with a name.",
                "The body is indented under the def line.",
                "Defining does nothing by itself. Calling it runs it: unlock()",
                "Write once, call as many times as you like.",
            ],
            "example": 'def greet():\n    print("hi")\n\ngreet()',
        },
        story="The lab's unlock routine is copied into fifty consoles. BYTE wants it written once and called.",
        goal="Define unlock() so it prints unlocked, then call it.",
        gameplay="Use the console and type three lines.",
        npcs=DOCTOR_LINES[4:] + DOCTOR_LINES[:4],
        dialogue=[
            "Wrap the spell in a def, then cast it by calling its name with parentheses.",
        ],
        challenge={
            "type": "python_lines",
            "prompt": "Line 1: define unlock(). Line 2 (indented): print unlocked. Line 3: call unlock().",
            "placeholder": "",
            "patterns": [
                {"regex": r"def\s+unlock\s*\(\s*\)\s*:"},
                {"regex": r"\s+print\(\s*([\"'])unlocked\1\s*\)"},
                {"regex": r"unlock\(\s*\)"},
            ],
        },
        reasoning="Separate defining behaviour from running it.",
        success="The routine runs and the door opens.",
        failure="The terminal reports which line is wrong.",
        explanation="def stores the code under a name; the call runs it. Without the call nothing happens.",
        reward="Grove Badge XIX",
        mentor="Ask why the door stays shut without the last line.",
        hints=["Defining a spell is not the same as casting it."],
        map=LAB_DEEP,
        theme="lab",
    ),

    level(
        25, "Parameters",
        section="Functions",
        start_items=["DAGGER"],
        objective="Pass a value into a function.",
        prerequisites=["def"],
        concepts=["parameters", "arguments"],
        lesson={
            "title": "Giving a function something to work with",
            "points": [
                "A parameter is a variable that belongs to the function: def greet(name):",
                "When you call greet(\"BYTE\"), name becomes \"BYTE\" inside the function.",
                "Same function, different input, different output.",
                "Cumulative: functions + variables + string joining.",
            ],
            "example": 'def greet(name):\n    print("Hello, " + name)\n\ngreet("Ada")   # Hello, Ada',
        },
        story="The greeter console says hello to everyone - as long as you tell it who.",
        goal="Give greet a parameter and call it with BYTE's name.",
        gameplay="Use the console and fill two blanks.",
        sign="GREETER: define greet with a name parameter, then greet \"BYTE\".",
        npcs=DOCTOR_LINES[1:] + DOCTOR_LINES[:1],
        dialogue=[
            "The function needs to be TOLD who to greet. That's what the parentheses carry.",
        ],
        challenge={
            "type": "fill_blank",
            "prompt": "Fill the parameter and the argument.",
            "code": ["def greet(___):", '    print("Hello, " + name)', "greet(___)"],
            "answers": [["name"], ['"BYTE"']],
            "bank": ["name", '"BYTE"', "greet", '"name"'],
        },
        reasoning="Match the parameter name used in the body and pass a string argument.",
        success="Hello, BYTE. The console opens the door.",
        failure="The console names the wrong blank.",
        explanation="The parameter name must match what the body uses; the call passes the actual text.",
        reward="Grove Badge XX",
        mentor="Ask what the body uses, and what the call must therefore provide.",
        hints=["Look at which variable the body already uses."],
        map=LAB_DEEP,
        theme="lab",
    ),

    # ===================== DEBUGGING =====================

    level(
        26, "Corrupted Terminal",
        section="Debugging",
        start_items=["DAGGER"],
        sign="CONSOLE LOG: SyntaxError on line 3. Read it character by character.",
        objective="Read an error and find the broken line.",
        prerequisites=["print()", "if"],
        concepts=["SyntaxError", "reading tracebacks"],
        lesson={
            "title": "Debugging - let the error point the way",
            "points": [
                "Errors tell you a line number. Start there.",
                "SyntaxError usually means something is unbalanced: ( ) \" \" :",
                "Read the line character by character. Count the pairs.",
                "Fix one thing, run again. Never change three things at once.",
            ],
            "example": "SyntaxError: '(' was never closed\n# look for a missing )",
        },
        story="NULL's static chewed one character out of a console. Python reports a SyntaxError on line 3.",
        goal="Find the broken line and say why it fails.",
        gameplay="Use the console: click the line, then choose the reason.",
        npcs=DOCTOR_LINES[6:] + DOCTOR_LINES[:6],
        dialogue=[
            "Python already told you the line. Now find out what's missing.",
        ],
        challenge={
            "type": "code_review",
            "label": "CODE",
            "prompt": "Click the broken line, then choose why it fails.",
            "code": ["code = 4172", "if code == 4172:", '    print("open"', 'print("done")'],
            "target_line": 3,
            "why_options": [
                "The closing parenthesis is missing",
                "code is text, not a number",
                "The if statement needs an else",
                "print is spelled wrong",
            ],
            "why_answer": 0,
            "fixed": ["code = 4172", "if code == 4172:", '    print("open")', 'print("done")'],
        },
        reasoning="Use the error as a pointer and check balance.",
        success="The console reboots clean.",
        failure="The console says that isn't the problem.",
        explanation="print(\"open\" never closes its parenthesis, so Python cannot finish the statement.",
        reward="Grove Badge XXI",
        mentor="Coach the player to count pairs; do not name the line.",
        hints=["Count what opens and what closes on the reported line."],
        map=LAB_DEEP,
        theme="lab",
    ),

    level(
        27, "The Loop That Never Ends",
        section="Debugging",
        start_items=["DAGGER"],
        sign="MONITOR: hissing for 6 hours. No error was raised.",
        objective="Find a logic bug: a loop that cannot stop.",
        prerequisites=["while", "variables"],
        concepts=["logic errors", "infinite loops"],
        lesson={
            "title": "Bugs without error messages",
            "points": [
                "Some bugs don't crash. The code runs - forever, or wrongly.",
                "For a while loop, ask: what makes the condition False? Does it ever happen?",
                "Trace the counter by hand for two or three passes.",
                "Cumulative: while + counters + comparisons.",
            ],
            "example": "count = 0\nwhile count < 3:\n    count = count + 1   # moves toward 3 - good",
        },
        story="A monitor has hissed for six hours. No error, no crash - just a loop that cannot end.",
        goal="Find the line that stops the loop from ever finishing.",
        gameplay="Use the monitor console: click the line, then choose the reason.",
        npcs=DOCTOR_LINES[7:] + DOCTOR_LINES[:7],
        dialogue=[
            "No error this time. Trace it. What does count do each pass?",
        ],
        challenge={
            "type": "code_review",
            "label": "CODE",
            "prompt": "Click the line that keeps the loop running forever, then choose why.",
            "code": ["count = 0", "while count < 3:", '    print("hiss")', "    count = count - 1"],
            "target_line": 4,
            "why_options": [
                "count moves away from 3, so the condition never becomes False",
                "print needs two arguments",
                "while must be replaced by for",
                "count should start at 3",
            ],
            "why_answer": 0,
            "fixed": ["count = 0", "while count < 3:", '    print("hiss")', "    count = count + 1"],
        },
        reasoning="Trace a counter and relate it to the stopping condition.",
        success="Silence. The monitor finally stops.",
        failure="The console says that isn't the problem.",
        explanation="count goes 0, -1, -2... it is always less than 3, so the loop never ends.",
        reward="Grove Badge XXII",
        mentor="Ask the player to write down count after each pass.",
        hints=["Which direction does count move each pass?"],
        map=LAB_DEEP,
        theme="lab",
    ),

    level(
        28, "Checkpoint: Functions & Debugging",
        kind="quiz",
        section="Debugging",
        objective="Prove you remember functions and debugging before moving on.",
        concepts=["def", "parameters", "calling", "SyntaxError", "tracing"],
        lesson={
            "title": "Checkpoint - Functions & Debugging",
            "points": ["def name(): defines; name() runs it.", "A parameter is a variable the function receives when called.", "SyntaxError usually means an unbalanced ( ) or quote - start at the reported line.", "Earlier: trace a loop counter by hand to find bugs that never crash."],
            "example": 'def greet(name):\n    print("Hello, " + name)\n\ngreet("BYTE")',
        },
        story="BYTE blocks the path with a drill. 'Quick check before the next zone. Four questions. No terminal - just you.'",
        goal="Answer every question correctly to unlock the next level.",
        gameplay="Read the recap, then answer four questions. One or two reach back to earlier sections.",
        dialogue=["Checkpoint drill. Answer all four and the path opens."],
        challenge={
            "type": "quiz",
            "prompt": "Answer all four questions. You can retry as often as you like.",
            "questions": [
                {"prompt": "def greet(): is written. What actually runs the function?", "options": ["def", "greet", "greet()", "print(greet)"], "answer": 2},
                {"prompt": "SyntaxError: '(' was never closed. Most likely cause?", "options": ["A variable is undefined", "A parenthesis is missing", "A loop runs forever", "The type is wrong"], "answer": 1},
                {"prompt": "What is a parameter?", "options": ["A variable the function receives", "A print inside a function", "A loop counter", "A file"], "answer": 0},
                {"prompt": "Earlier section: count = 0, while count < 3, and inside count = count - 1. What happens?", "options": ["Stops after 3 passes", "Never runs", "Runs forever", "SyntaxError"], "answer": 2}
            ],
        },
        reasoning="Retrieval practice on the latest section, plus one or two cumulative questions.",
        success="All four correct - the path opens.",
        failure="The drill says which question is wrong, nothing more.",
        explanation="Calling runs a function; parameters carry input; errors point to a line; counters must move toward the exit.",
        reward="Checkpoint Pin VI",
        mentor="Coach with questions; never state the answer.",
        hints=["Re-read the lesson notes of the levels in this section."],
        theme="lab",
    ),

    # ===================== FINAL =====================

    level(
        29, "Final Grove Trial",
        section="Final Trial",
        start_items=["DAGGER"],
        sign="MASTER CONSOLE: define the tool first, then use it in a loop.",
        objective="Combine functions, conditions and loops.",
        prerequisites=["def", "if / else", "for"],
        concepts=["putting it together"],
        lesson={
            "title": "Everything at once",
            "points": [
                "A function can contain an if/else. A loop can call a function.",
                "Indentation tells the whole story: what is inside what.",
                "def first, its body under it, then the loop that uses it.",
                "This is the shape of most real programs: define tools, then use them.",
            ],
            "example": 'def check(code):\n    if code == 4172:\n        print("open")\n    else:\n        print("denied")\n\nfor attempt in range(3):\n    check(4172)',
        },
        story="The lab's master console. Seven lines, scrambled by NULL. Put them right and the way out of the Grove opens.",
        goal="Order all seven lines into a working program.",
        gameplay="Use the master console and drag seven lines into place.",
        npcs=DOCTOR_LINES,
        dialogue=[
            "Everything you learned, in one program. Define the tool, then loop and use it.",
        ],
        challenge={
            "type": "order_code",
            "prompt": "Drag all seven lines into a working program.",
            "pieces": [
                "def check(code):",
                "    if code == 4172:",
                '        print("open")',
                "    else:",
                '        print("denied")',
                "for attempt in range(3):",
                "    check(4172)",
            ],
            "shuffle": [5, 2, 0, 6, 3, 1, 4],
        },
        reasoning="Compose def, nested if/else, and a loop that calls the function.",
        success="open, open, open. The Grove is complete.",
        failure="The console says the order isn't right.",
        explanation="The function is defined first; its if/else body sits under it; the loop then calls it three times.",
        reward="Grove Master Badge",
        mentor="Help the player trace one loop pass by hand.",
        hints=["Which lines are indented twice? They belong inside something indented once."],
        map=LAB_DEEP,
        theme="lab",
    ),
]
