"""
Secure Coding - The Foundry. Ten levels, data only.
"""

from courses.common import level


SECURE_LEVELS = [

    level(
        1, "What Makes Code Insecure?",
        objective="Understand that insecure code trusts things it should not.",
        concepts=["trust boundaries", "assumptions", "attacker mindset"],
        story="The Foundry forges the Academy's own code. BYTE: 'Bugs are mistakes. Vulnerabilities are mistakes an attacker can use.'",
        goal="Identify the root cause of most vulnerabilities.",
        learn=["Insecure code trusts input, hides secrets badly, or skips checks.", "Ask: what if the input is not what I expect?"],
        example='age = input()   # what if age is "abc" or 10000 lines long?',
        dialogue=["Welcome to the Foundry.", "Most holes come from one habit. Which?"],
        challenge={
            "type": "mcq",
            "prompt": "The most common root cause of insecure code is:",
            "options": ["Using too many comments", "Trusting input and skipping checks", "Long variable names", "Using functions"],
            "answer": 1,
            "wrong": "Style does not create holes. Misplaced trust does.",
        },
        reasoning="Framing security as managing trust.",
        success="The forge lights.",
        failure="Feedback restates trust boundaries.",
        explanation="Code that assumes input is safe, or that secrets stay hidden, is where attackers dig.",
        reward="Foundry Badge I",
        mentor="Explain trust boundaries using the app's own signup validation.",
        hints=["What do attackers control? Input."],
        intro=True,
    ),

    level(
        2, "Input Validation",
        objective="Spot code that uses input without checking it.",
        prerequisites=["trust boundaries"],
        concepts=["validation", "allow-lists", "length limits"],
        story="A forge terminal takes an age and builds a badge - with no checks.",
        goal="Find the line that trusts input and say why it is dangerous.",
        learn=["Validate at the boundary: type, range, length, allowed values.", "Reject what you do not expect."],
        example='age = int(input())\nif not 0 < age < 150:\n    print("invalid")',
        dialogue=["This terminal believes whatever it is told.", "Find the line that trusts too much."],
        challenge={
            "type": "code_review",
            "label": "CODE",
            "prompt": "Click the dangerous line, then choose why.",
            "code": [
                'print("Badge maker")',
                "age = input(\"Age: \")",
                "years_left = 150 - int(age)",
                'print("Years of study left:", years_left)',
            ],
            "target_line": 3,
            "why_options": [
                "age is used as a number without checking it is a valid number in range",
                "print should not be used",
                "150 is too small a number",
                "Variables cannot be named age",
            ],
            "why_answer": 0,
            "fixed": [
                "age = input(\"Age: \")",
                "if not age.isdigit() or not 0 < int(age) < 150:",
                '    print("Please enter a valid age")',
                "else:",
                "    years_left = 150 - int(age)",
            ],
        },
        reasoning="Seeing where untrusted data enters and where it is used.",
        success="The badge maker now rejects nonsense.",
        failure="Feedback: where is input first used as something it might not be?",
        explanation="int(age) crashes on text and accepts absurd values. Validate type and range before using input.",
        reward="Foundry Badge II",
        mentor="Discuss what inputs could break the code; guide toward range checks.",
        hints=["Which line converts the input?"],
    ),

    level(
        3, "Hardcoded Secrets",
        objective="Recognise secrets written into source code.",
        concepts=["secrets", "environment variables", ".env"],
        story="A forge script carries its key etched into the metal. Anyone who copies it owns the key.",
        goal="Find the hardcoded secret and explain the risk.",
        learn=["Never put API keys or passwords in code.", "Load them from the environment (this app uses .env + os.getenv)."],
        example='api_key = os.getenv("ANTHROPIC_API_KEY")   # good\napi_key = "sk-live-..."                    # bad',
        dialogue=["Secrets in code get copied, shared, and leaked.", "Which line is the leak?"],
        challenge={
            "type": "code_review",
            "label": "CODE",
            "prompt": "Click the dangerous line, then choose why.",
            "code": [
                "import requests",
                'API_KEY = "sk-live-FAKE-1234567890"',
                "def fetch():",
                '    return requests.get(URL, headers={"key": API_KEY})',
            ],
            "target_line": 2,
            "why_options": [
                "The key is written in the code, so anyone with the code has the key",
                "Uppercase names are not allowed",
                "requests is insecure",
                "Functions should not return values",
            ],
            "why_answer": 0,
            "fixed": [
                "import os, requests",
                'API_KEY = os.getenv("API_KEY")',
                "if not API_KEY:",
                '    raise RuntimeError("API_KEY missing")',
            ],
        },
        reasoning="Separating configuration from code.",
        success="The key is moved to the environment.",
        failure="Feedback: which line would you regret sharing?",
        explanation="Hardcoded secrets end up in git history, screenshots and backups. Environment variables keep them out of code.",
        reward="Foundry Badge III",
        mentor="Relate to mentor.py's use of .env; never ask for real keys.",
        hints=["Look for a long random-looking string."],
    ),

    level(
        4, "Authentication Mistakes",
        objective="Spot login logic that can be bypassed.",
        prerequisites=["authentication"],
        concepts=["checking credentials", "bypass logic"],
        story="A guard script lets 'admin' in without a password.",
        goal="Find the bypass.",
        learn=["Every login must check the secret, not just the name.", "Do not special-case users."],
        example='if check_password_hash(stored, given):\n    login()',
        dialogue=["This guard knows names, not secrets.", "Which line lets anyone in as admin?"],
        challenge={
            "type": "code_review",
            "label": "CODE",
            "prompt": "Click the dangerous line, then choose why.",
            "code": [
                "def login(username, password):",
                '    if username == "admin":',
                "        return True",
                "    return check_password(username, password)",
            ],
            "target_line": 2,
            "why_options": [
                "Anyone who types admin is logged in without a password check",
                "Function names cannot be login",
                "return True is always insecure",
                "Passwords should be printed for debugging",
            ],
            "why_answer": 0,
            "fixed": [
                "def login(username, password):",
                "    return check_password(username, password)",
            ],
        },
        reasoning="Reading control flow like an attacker.",
        success="The guard checks everyone.",
        failure="Feedback: trace what happens when username is admin.",
        explanation="The special case skips the password entirely. Authentication must always verify the secret.",
        reward="Foundry Badge IV",
        mentor="Ask the player to trace the function with username = admin.",
        hints=["Which branch returns before checking the password?"],
    ),

    level(
        5, "Password Storage",
        objective="Know why passwords must be hashed, never stored in plaintext.",
        prerequisites=["authentication mistakes"],
        concepts=["hashing", "salting", "werkzeug generate_password_hash"],
        story="An old forge ledger stores every password in plain text. One leak = every account gone.",
        goal="Find the plaintext storage line.",
        learn=["Store a salted hash, never the password.", "This app uses generate_password_hash() and check_password_hash()."],
        example='hashed = generate_password_hash(password)\nstore(username, hashed)',
        dialogue=["Plaintext passwords are a gift to attackers.", "Which line stores the raw secret?"],
        challenge={
            "type": "code_review",
            "label": "CODE",
            "prompt": "Click the dangerous line, then choose why.",
            "code": [
                "def signup(username, password):",
                "    conn = get_db()",
                '    conn.execute("INSERT INTO users VALUES (?, ?)", (username, password))',
                "    conn.commit()",
            ],
            "target_line": 3,
            "why_options": [
                "The raw password is saved; a database leak exposes every account",
                "SQL should not use question marks",
                "commit is unnecessary",
                "Usernames must be hashed instead",
            ],
            "why_answer": 0,
            "fixed": [
                "    password_hash = generate_password_hash(password)",
                '    conn.execute("INSERT INTO users VALUES (?, ?)", (username, password_hash))',
            ],
        },
        reasoning="Understanding that hashing is one-way so leaks reveal nothing usable.",
        success="The ledger now holds only hashes.",
        failure="Feedback: what exactly gets written to the database?",
        explanation="Hashing is one-way; even with the database, attackers cannot read passwords. Salt stops precomputed tables.",
        reward="Foundry Badge V",
        mentor="Show how app.py does it correctly; explain one-way functions.",
        hints=["Look at what value is inserted."],
    ),

    level(
        6, "Injection Concepts",
        objective="Recognise SQL built by gluing strings together.",
        prerequisites=["input validation"],
        concepts=["SQL injection", "parameterised queries"],
        story="A search terminal glues the player's words straight into a database command.",
        goal="Find the injectable line.",
        learn=["Never build queries with + or f-strings and user input.", "Use placeholders (?) so input is treated as data, not commands."],
        example='conn.execute("SELECT * FROM users WHERE name = ?", (name,))',
        dialogue=["If input becomes part of the command, input can BE a command.", "Which line glues them together?"],
        challenge={
            "type": "code_review",
            "label": "CODE",
            "prompt": "Click the dangerous line, then choose why.",
            "code": [
                "name = request.form.get(\"name\")",
                "conn = get_db()",
                'query = "SELECT * FROM users WHERE name = \'" + name + "\'"',
                "rows = conn.execute(query).fetchall()",
            ],
            "target_line": 3,
            "why_options": [
                "User input is pasted into the SQL text, so it can change the command",
                "SELECT is slower than INSERT",
                "fetchall returns too much",
                "Variables named query are reserved",
            ],
            "why_answer": 0,
            "fixed": [
                'rows = conn.execute("SELECT * FROM users WHERE name = ?", (name,)).fetchall()',
            ],
        },
        reasoning="Seeing data and command mixing.",
        success="The terminal uses placeholders.",
        failure="Feedback: which line contains + with user input?",
        explanation="With placeholders the database never confuses input with SQL. This app already does this everywhere.",
        reward="Foundry Badge VI",
        mentor="Explain data vs command separation; do not craft attack payloads.",
        hints=["Look for string gluing with +."],
    ),

    level(
        7, "Secure Defaults",
        objective="Identify unsafe defaults left on in production.",
        concepts=["debug mode", "default deny", "least privilege"],
        story="A forge server ships with every hatch open 'for convenience'.",
        goal="Find the unsafe default.",
        learn=["Ship with the safest setting on: debug off, deny by default, minimal permissions.", "Convenience settings are for development only."],
        example="app.run(debug=False)   # in production",
        dialogue=["Defaults decide what happens when nobody is looking.", "Which line leaves a hatch open?"],
        challenge={
            "type": "code_review",
            "label": "CODE",
            "prompt": "Click the dangerous line, then choose why.",
            "code": [
                "app = Flask(__name__)",
                "ALLOW_ALL_USERS_TO_DELETE = True",
                'app.secret_key = os.getenv("SECRET_KEY")',
                "app.run(debug=False)",
            ],
            "target_line": 2,
            "why_options": [
                "A permissive default gives everyone a dangerous permission",
                "Flask apps cannot have constants",
                "secret_key should be hardcoded",
                "debug must be True in production",
            ],
            "why_answer": 0,
            "fixed": ["ALLOW_ALL_USERS_TO_DELETE = False   # grant per role instead"],
        },
        reasoning="Least privilege as a default.",
        success="Hatches closed.",
        failure="Feedback: which setting grants the most power to the most people?",
        explanation="Secure by default means dangerous abilities are off until explicitly granted to the right role.",
        reward="Foundry Badge VII",
        mentor="Discuss debug=True risks and least privilege.",
        hints=["Which line says everyone can do something destructive?"],
    ),

    level(
        8, "Code Review",
        objective="Review a snippet and prioritise the worst issue.",
        prerequisites=["secrets", "injection", "validation"],
        concepts=["prioritisation", "review checklist"],
        story="Three apprentices submitted code. You have time to flag one thing. Pick the worst.",
        goal="Find the most severe line.",
        learn=["Review checklist: input trusted? secrets in code? queries glued? checks skipped?", "Fix the most damaging issue first."],
        example="Severity: injection > hardcoded secret > missing length check",
        dialogue=["Reviewers prioritise. Not every issue is equal.", "Which line hurts the most?"],
        challenge={
            "type": "code_review",
            "label": "CODE",
            "prompt": "Click the MOST severe line, then choose why.",
            "code": [
                "user = request.form.get(\"user\")",
                'note = request.form.get("note")',
                'conn.execute(f"DELETE FROM notes WHERE owner = \'{user}\'")',
                "print(\"deleted\")",
            ],
            "target_line": 3,
            "why_options": [
                "An f-string builds SQL from input: injection could delete everything",
                "print is noisy",
                "note is unused",
                "DELETE is always forbidden",
            ],
            "why_answer": 0,
            "fixed": ['conn.execute("DELETE FROM notes WHERE owner = ?", (user,))'],
        },
        reasoning="Ranking severity.",
        success="The worst issue is caught before merge.",
        failure="Feedback: which line lets input change a database command?",
        explanation="Injection in a DELETE is catastrophic; unused variables and prints are cosmetic.",
        reward="Foundry Badge VIII",
        mentor="Help the player rank issues; ask 'what is the blast radius?'",
        hints=["Recall level 6."],
    ),

    level(
        9, "AI-Generated Code Risks",
        objective="Verify AI-suggested code instead of trusting it.",
        prerequisites=["code review"],
        concepts=["AI assistance", "verification", "prompt injection"],
        story="An AI helper (like SecureMentor) suggested a 'quick calculator'. It looks fine. It is not.",
        goal="Find the dangerous line in the AI's suggestion.",
        learn=[
            "AI code can be confident and wrong. Review it like a stranger's code.",
            "eval()/exec() on input = running whatever the user types.",
            "Prompt injection: text inside data can try to steer an AI. Treat data as data.",
        ],
        example="# never: eval(user_input)\n# instead: parse numbers and use +, -, *",
        dialogue=["The AI wrote this. Confident, tidy... and it runs anything a user types.", "Find the line. Then remember: verify, don't trust."],
        challenge={
            "type": "code_review",
            "label": "AI SUGGESTION",
            "prompt": "Click the dangerous line, then choose why.",
            "code": [
                "# AI: here is a simple calculator",
                'expr = input("Enter expression: ")',
                "result = eval(expr)",
                'print("Result:", result)',
            ],
            "target_line": 3,
            "why_options": [
                "eval runs any code the user types - arbitrary code execution",
                "Comments are dangerous",
                "input must be called twice",
                "print cannot show numbers",
            ],
            "why_answer": 0,
            "fixed": [
                "a = float(input(\"First number: \"))",
                "b = float(input(\"Second number: \"))",
                "print(\"Sum:\", a + b)",
            ],
        },
        reasoning="Treating AI output as untrusted input to review.",
        success="The calculator is rewritten safely.",
        failure="Feedback: which function turns text into running code?",
        explanation="eval executes text as Python. AI suggestions must be verified; and any text an AI reads (including user data) may contain injected instructions - keep instructions and data separate.",
        reward="Foundry Badge IX",
        mentor="Explain eval risk and prompt injection; encourage verifying AI code with tests and review.",
        hints=["One function name means 'evaluate this text as code'."],
    ),

    level(
        10, "Final Vulnerability Investigation",
        objective="Find the critical flaw in a realistic snippet.",
        prerequisites=["all Foundry levels"],
        concepts=["end-to-end review"],
        story="NULL slipped a change into the Academy's own login code. Find it before it ships.",
        goal="Find the line that breaks authentication.",
        learn=["Review the whole flow: input -> check -> store -> respond."],
        example="Look for any path that logs in without verifying the hash.",
        dialogue=["This is the Academy's real login shape. One line is poisoned.", "Trace every path to session[\"user_id\"]."],
        challenge={
            "type": "code_review",
            "label": "CODE",
            "prompt": "Click the poisoned line, then choose why.",
            "code": [
                "user = conn.execute(\"SELECT * FROM users WHERE username = ?\", (username,)).fetchone()",
                "if user is None:",
                "    return error(\"Username or password is incorrect.\")",
                "if password == \"\" or check_password_hash(user[\"password_hash\"], password):",
                "    session[\"user_id\"] = user[\"id\"]",
            ],
            "target_line": 4,
            "why_options": [
                "An empty password logs anyone in - the hash check is bypassed",
                "fetchone should be fetchall",
                "Error messages must reveal which field is wrong",
                "session cannot store integers",
            ],
            "why_answer": 0,
            "fixed": [
                "if check_password_hash(user[\"password_hash\"], password):",
                "    session[\"user_id\"] = user[\"id\"]",
            ],
        },
        reasoning="Boolean logic review: an OR with a trivially true branch.",
        success="The poisoned line is removed. The Foundry is secure.",
        failure="Feedback: read the condition with an empty password.",
        explanation="or short-circuits: with an empty password the left side is True and the hash is never checked.",
        reward="Foundry Master Badge",
        mentor="Ask the player to evaluate the condition with password = \"\".",
        hints=["Try password = \"\" in your head."],
        boss=True,
    ),
]
